import { all, insert, one, run } from './db.js';
import { audit } from './audit.js';
import { validatePassword, sha256 } from './crypto.js';
import { edgeHashPassword, edgeVerifyPassword } from './auth_crypto.js';
import { authBot, tgSend } from './telegram.js';
import { chatCode, clientIp, isoAfter, nowIso, randomCode, randomToken } from './util.js';
import { setSessionUser, rotateSession } from './session.js';

export async function sessionUser(env,s){if(!s?.row?.user_id)return null;const u=await one(env,"SELECT * FROM users WHERE id=? AND status='active'",[s.row.user_id]);return u||null;}
export async function register(env,ctx,req,{name,email,password,telegram}){
  email=String(email||'').trim().toLowerCase();name=String(name||'').trim();if(!name||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw new Error('Nama/email tidak valid.');const pe=validatePassword(password);if(pe)throw new Error(pe);if(await one(env,'SELECT id FROM users WHERE email=?',[email]))throw new Error('Email sudah terdaftar.');
  const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)+'-'+randomToken(4).slice(0,6);const t=nowIso();
  const tid=await insert(env,"INSERT INTO tenants(name,slug,status,created_at) VALUES(?,?,'active',?)",[name,slug,t]);const uid=await insert(env,"INSERT INTO users(tenant_id,name,email,password_hash,role,status,telegram_username,created_at) VALUES(?,?,?,?, 'owner','pending',?,?)",[tid,name,email,await edgeHashPassword(env,password),String(telegram||'').replace(/^@/,''),t]);
  await run(env,"INSERT INTO user_preferences(user_id,theme,sound,notifications_json,updated_at) VALUES(?,'system','soft','{}',?)",[uid,t]);const bronze=await one(env,"SELECT id FROM plans WHERE name='Bronze'");await run(env,"INSERT INTO subscriptions(tenant_id,plan_id,status,starts_at,ends_at,created_at) VALUES(?,?,'trial',?,?,?)",[tid,bronze.id,t,isoAfter(7*86400),t]);
  const token=randomToken(40).slice(0,60);await run(env,"INSERT INTO telegram_links(user_id,token,purpose,expires_at,created_at) VALUES(?,?,'register',?,?)",[uid,token,isoAfter(1800),t]);await audit(env,ctx,{event:'REGISTER_CREATED',risk:20,metadata:{email},tenantId:tid,userId:uid,request:req});return {user_id:uid,token};
}
export async function pairTelegram(env,ctx,req,token,from,chatId){
  const link=await one(env,'SELECT * FROM telegram_links WHERE token=? AND used_at IS NULL AND expires_at>?',[token,nowIso()]);if(!link)return false;
  const t=nowIso();await run(env,'UPDATE users SET telegram_user_id=?,telegram_chat_id=?,telegram_username=?,telegram_verified_at=? WHERE id=?',[String(from.id),String(chatId||from.id),from.username||null,t,link.user_id]);await run(env,'UPDATE telegram_links SET used_at=? WHERE id=?',[t,link.id]);if(link.purpose!=='link_only')await issueOtp(env,link.user_id,link.purpose==='team'?'register':link.purpose);const u=await one(env,'SELECT tenant_id FROM users WHERE id=?',[link.user_id]);await audit(env,ctx,{event:'TELEGRAM_LINKED',risk:15,metadata:{telegram_user_id:String(from.id)},tenantId:u?.tenant_id,userId:link.user_id,request:req});return true;
}
export async function issueOtp(env,userId,purpose){
  const u=await one(env,'SELECT * FROM users WHERE id=?',[userId]);const bot=await authBot(env);if(!u||!bot||!u.telegram_chat_id)return false;const since=new Date(Date.now()-15*60*1000).toISOString().replace('T',' ').replace('Z','').slice(0,19);const recent=await one(env,'SELECT COUNT(*) c FROM otp_codes WHERE user_id=? AND purpose=? AND created_at>=?',[userId,purpose,since]);if(Number(recent?.c||0)>=5)return false;
  await run(env,'UPDATE otp_codes SET used_at=? WHERE user_id=? AND purpose=? AND used_at IS NULL',[nowIso(),userId,purpose]);const code=randomCode();await run(env,'INSERT INTO otp_codes(user_id,purpose,code_hash,expires_at,created_at) VALUES(?,?,?,?,?)',[userId,purpose,await sha256(code),isoAfter(300),nowIso()]);const labels={register:'Pendaftaran',login:'Login',reset:'Reset Password'};const r=await tgSend(bot.token,u.telegram_chat_id,`🔐 <b>JOPUJA LIVE CONNECT</b>\n${labels[purpose]||purpose} OTP: <code>${code}</code>\nBerlaku 5 menit. Jangan berikan kode ini kepada siapa pun.`);return !!r.ok;
}
export async function verifyOtp(env,userId,purpose,code){const otp=await one(env,'SELECT * FROM otp_codes WHERE user_id=? AND purpose=? AND used_at IS NULL ORDER BY id DESC LIMIT 1',[userId,purpose]);if(!otp||otp.expires_at<nowIso()||Number(otp.attempts)>=5)return false;await run(env,'UPDATE otp_codes SET attempts=attempts+1 WHERE id=?',[otp.id]);if(await sha256(String(code||''))!==otp.code_hash)return false;await run(env,'UPDATE otp_codes SET used_at=? WHERE id=?',[nowIso(),otp.id]);return true;}
export async function beginLogin(env,ctx,req,s,email,password){email=String(email||'').trim().toLowerCase();const since=new Date(Date.now()-15*60*1000).toISOString().replace('T',' ').replace('Z','').slice(0,19);const rl=await one(env,'SELECT COUNT(*) c FROM login_attempts WHERE identity=? AND ip=? AND ok=0 AND created_at>=?',[email,clientIp(req),since]);if(Number(rl?.c||0)>=7)throw new Error('Terlalu banyak percobaan. Coba lagi beberapa menit.');const u=await one(env,'SELECT * FROM users WHERE email=?',[email]);const ok=!!u&&await edgeVerifyPassword(env,password,u.password_hash);await run(env,'INSERT INTO login_attempts(identity,ip,ok,created_at) VALUES(?,?,?,?)',[email,clientIp(req),ok?1:0,nowIso()]);if(!ok)throw new Error('Email atau password salah.');if(u.status==='pending')throw new Error('Akun belum menyelesaikan verifikasi Telegram.');if(!u.telegram_chat_id)throw new Error('Telegram belum terhubung.');if(!await issueOtp(env,u.id,'login'))throw new Error('OTP Telegram gagal dikirim. Periksa bot autentikasi.');s.data.pending_login=u.id;s.dirty=true;await audit(env,ctx,{event:'LOGIN_PASSWORD_OK',risk:15,tenantId:u.tenant_id,userId:u.id,request:req});return u;}
export async function completeLogin(env,ctx,req,s,code){const id=Number(s.data.pending_login||0);if(!id||!await verifyOtp(env,id,'login',code))return false;delete s.data.pending_login;await rotateSession(env,s,id);await run(env,'UPDATE users SET last_login_at=? WHERE id=?',[nowIso(),id]);const u=await one(env,'SELECT * FROM users WHERE id=?',[id]);await audit(env,ctx,{event:'LOGIN_SUCCESS',risk:10,tenantId:u.tenant_id,userId:id,request:req});return true;}
export async function activateRegistration(env,ctx,req,s,uid,code){if(!await verifyOtp(env,uid,'register',code))return false;await run(env,"UPDATE users SET status='active' WHERE id=?",[uid]);await rotateSession(env,s,uid);const u=await one(env,'SELECT * FROM users WHERE id=?',[uid]);await audit(env,ctx,{event:'REGISTER_VERIFIED',risk:5,tenantId:u.tenant_id,userId:uid,request:req});return true;}
