import { ensureSchema, all, one, run, insert, setting, setSetting } from './db.js';
import { LiveHub, hubBroadcast, hubStub } from './realtime.js';
import { AuthCrypto, edgeHashPassword, vaultEncrypt, vaultDecrypt, vaultDigest, vaultReady } from './auth_crypto.js';
import { loadSession, saveSession, attachSession, destroySession, csrfField, csrfOk, rotateSession } from './session.js';
import { sessionUser, register, pairTelegram, issueOtp, verifyOtp, beginLogin, completeLogin, activateRegistration } from './auth.js';
import { currentPlan, allowResource } from './plan.js';
import { can } from './permissions.js';
import { audit } from './audit.js';
import { validatePassword, secretToken, sha256 } from './crypto.js';
import { authBot, saveAuthBot, domainBot, tgCall, tgSend, normalizeToken } from './telegram.js';
import { e, attr, json, html, redirect, text, form, nowIso, isoAfter, randomToken, chatCode, baseUrl, normalizeDomain, sameDomain, originHost, clientIp, ua, cfCountry, money, selected, checked, sanitizeColor, safeInt, cap, securityHeaders } from './util.js';

export { LiveHub, AuthCrypto };

export default {
  async fetch(request,env,ctx){
    const url=new URL(request.url), path=url.pathname;
    if(path.startsWith('/assets/')||path==='/widget.js'||path==='/favicon.ico') return env.ASSETS.fetch(request);
    try{
      await ensureSchema(env);
      if(path==='/health')return securityHeaders(json({ok:true,app:env.APP_NAME||'JOPUJA LIVE CONNECT',version:env.APP_VERSION||'2.1.0',runtime:'Cloudflare Workers',database:'D1',storage:'R2',realtime:'Durable Objects',time:nowIso()}));
      if(path.startsWith('/webhook/'))return await webhookRoute(request,env,ctx,url);
      if(path.startsWith('/api/widget/'))return await widgetApi(request,env,ctx,url);
      if(path.startsWith('/api/v1/'))return await apiV1(request,env,ctx,url);
      if(path.startsWith('/widget-media/'))return await widgetMedia(request,env,url);
      if(path==='/ws/widget')return await wsWidget(request,env,url);
      const session=await loadSession(request,env,{create:true});
      const user=await sessionUser(env,session);
      let response;
      if(path.startsWith('/api/dashboard/')) response=await dashboardApi(request,env,ctx,url,session,user);
      else if(path==='/ws/dashboard') response=await wsDashboard(request,env,url,session,user);
      else if(path.startsWith('/media/')) response=await mediaRoute(request,env,url,user);
      else response=await pageRoute(request,env,ctx,url,session,user);
      if(session.dirty)await saveSession(env,session);
      return securityHeaders(attachSession(response,session));
    }catch(err){
      const msg=String(err?.stack||err?.message||err);console.error(msg);
      return securityHeaders(html(`<div style="font-family:system-ui;padding:32px"><h1>JOPUJA LIVE CONNECT</h1><p>Terjadi error aplikasi.</p><pre style="white-space:pre-wrap;background:#111;color:#eee;padding:16px;border-radius:12px">${e(String(err?.message||err))}</pre></div>`,500));
    }
  },
  async scheduled(controller,env,ctx){
    await ensureSchema(env);ctx.waitUntil(maintenance(env,controller.cron).catch(console.error));
  }
};

async function pageRoute(req,env,ctx,url,s,user){
  const p=url.pathname,m=req.method;
  const installed=await one(env,"SELECT id FROM users WHERE role='super_admin' LIMIT 1");
  if(!installed&&p!=='/install')return redirect('/install');
  if(p==='/install')return installPage(req,env,ctx,s,installed);
  if(p==='/')return user?redirect(user.role==='super_admin'?'/admin':'/dashboard'):homePage(req,env,s);
  if(p==='/register')return registerPage(req,env,ctx,s,user);
  if(p==='/telegram/connect')return telegramConnectPage(req,env,s,url);
  if(p==='/register/verify')return registerVerify(req,env,ctx,s);
  if(p==='/join')return joinPage(req,env,ctx,s,user,url);
  if(p==='/login')return loginPage(req,env,ctx,s,user);
  if(p==='/login/otp')return loginOtpPage(req,env,ctx,s);
  if(p==='/forgot')return forgotPage(req,env,s);
  if(p==='/reset')return resetPage(req,env,ctx,s);
  if(p==='/logout'){await audit(env,ctx,{event:'LOGOUT',risk:0,tenantId:user?.tenant_id,userId:user?.id,request:req});await destroySession(env,s);return attachSession(redirect('/login'),s,{destroy:true});}
  if(!user)return redirect('/login');
  if(p==='/dashboard')return dashboardPage(req,env,s,user);
  if(p==='/inbox')return inboxPage(req,env,s,user,url);
  if(p==='/domains')return domainsPage(req,env,ctx,s,user);
  if(p==='/bots')return botsPage(req,env,ctx,s,user);
  if(p==='/widget')return widgetPage(req,env,ctx,s,user,url);
  if(p==='/team')return teamPage(req,env,ctx,s,user);
  if(p==='/analytics')return analyticsPage(req,env,s,user);
  if(p==='/visitors')return visitorsPage(req,env,s,user);
  if(p==='/notifications')return notificationsPage(req,env,ctx,s,user);
  if(p==='/automation')return automationPage(req,env,ctx,s,user);
  if(p==='/api-webhooks')return apiWebhooksPage(req,env,ctx,s,user);
  if(p==='/subscription')return subscriptionPage(req,env,ctx,s,user);
  if(p==='/diagnostics')return diagnosticsPage(req,env,s,user);
  if(p==='/settings')return settingsPage(req,env,ctx,s,user);
  if(p.startsWith('/admin'))return adminPage(req,env,ctx,s,user,url);
  return render(req,env,s,user,'404','<div class="empty center"><h1>404</h1><p>Halaman tidak ditemukan.</p></div>',false,false,404);
}

function flash(s,type,msg){s.data.flashes=s.data.flashes||[];s.data.flashes.push([type,msg]);s.dirty=true;}
function flashes(s){const f=s.data.flashes||[];delete s.data.flashes;if(f.length)s.dirty=true;return f;}
function alertHtml(s,err=''){let h=err?`<div class="alert error">${e(err)}</div>`:'';for(const [t,m] of flashes(s))h+=`<div class="alert ${e(t)}">${e(m)}</div>`;return h;}
function forbidden(){return html('<h1>403 Forbidden</h1>',403);}

async function render(req,env,s,user,title,body,app=false,admin=false,status=200){
  let theme='system',sound='soft',soundUrl='';
  if(user){const pref=await one(env,'SELECT * FROM user_preferences WHERE user_id=?',[user.id]);theme=pref?.theme||'system';sound=pref?.sound||'soft';if(pref?.sound_asset_key)soundUrl=`/media/${encodeURIComponent(pref.sound_asset_key)}`;}
  let nav='';
  if(app&&user){
    const items=admin?
      [['/admin','Overview','◉'],['/admin/users','Users','◎'],['/admin/plans','Plans','◇'],['/admin/subscriptions','Subscriptions','↗'],['/admin/logs','Audit','⌁'],['/admin/settings','Settings','⚙']]:
      [['/dashboard','Overview','◉'],['/inbox','Live Chat','◇'],['/analytics','Traffic','↗'],['/visitors','Visitors','◌'],['/domains','Domains','⌁'],['/widget','Widget','◈'],['/bots','Telegram','✦'],['/team','Team','◎'],['/notifications','Notifikasi','♫'],['/automation','Automation','⚡'],['/api-webhooks','API & Webhook','↯'],['/diagnostics','Diagnosis','⊹'],['/subscription','Langganan','◆'],['/settings','Settings','⚙']];
    const links=items.map(i=>`<a class="nav-link ${new URL(req.url).pathname===i[0]?'active':''}" href="${i[0]}"><span>${i[2]}</span><b>${i[1]}</b></a>`).join('');
    nav=`<aside class="sidebar"><a class="logo" href="${admin?'/admin':'/dashboard'}"><span>JL</span><div>JOPUJA<b>LIVE CONNECT</b></div></a><nav>${links}</nav><a class="nav-link logout" href="/logout"><span>↪</span><b>Logout</b></a></aside><header class="topbar"><button id="menuToggle" class="icon-btn">☰</button><div class="top-spacer"></div><button id="themeToggle" class="icon-btn">◐</button><div class="profile-mini"><span>${e(user.name.slice(0,1).toUpperCase())}</span><div><b>${e(user.name)}</b><small>${e(user.role)}</small></div></div></header>`;
  }
  const full=`<!doctype html><html lang="id" data-theme="${e(theme)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark light"><meta name="robots" content="noindex,nofollow"><title>${e(title)} • JOPUJA LIVE CONNECT</title><link rel="stylesheet" href="/assets/app.css"></head><body class="${app?'app-shell':'public-shell'}" data-sound="${e(sound)}" data-sound-url="${e(soundUrl)}">${nav}<main class="${app?'app-main':'public-main'}">${alertHtml(s)}${body}<footer class="footer">JOPUJA LIVE CONNECT • BY JOPUJA FOUNDER • Credit Jopuja Digital™</footer></main><script src="/assets/app.js" defer></script></body></html>`;
  return html(full,status);
}

async function installPage(req,env,ctx,s,installed){
  if(installed)return redirect('/login');let err='';
  if(req.method==='POST'){
    const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else try{
      const name=cap(b.name,120).trim(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(!name||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw new Error('Nama/email tidak valid.');const pe=validatePassword(password);if(pe)throw new Error(pe);
      const t=nowIso(),tid=await insert(env,"INSERT INTO tenants(name,slug,status,created_at) VALUES(?,?,'active',?)",[name,'system-admin',t]);const uid=await insert(env,"INSERT INTO users(tenant_id,name,email,password_hash,role,status,created_at) VALUES(?,?,?,?, 'super_admin','active',?)",[tid,name,email,await edgeHashPassword(env,password),t]);await run(env,"INSERT INTO user_preferences(user_id,theme,sound,notifications_json,updated_at) VALUES(?,'system','soft','{}',?)",[uid,t]);await rotateSession(env,s,uid);await audit(env,ctx,{event:'SYSTEM_INSTALLED',risk:0,tenantId:tid,userId:uid,request:req});return redirect('/admin/settings');
    }catch(x){err=x.message;}
  }
  const body=`<div class="auth-card wide"><div class="brand-mark">JL</div><h1>JOPUJA LIVE CONNECT</h1><p class="muted">Cloudflare Auto Installer • Workers + D1 + R2 + Durable Objects • Zero Secret Setup</p>${err?`<div class="alert error">${e(err)}</div>`:''}<div class="env-grid"><div class="env-item"><span class="diag-icon ok">✓</span><div><b>Runtime</b><small>Cloudflare Workers</small></div></div><div class="env-item"><span class="diag-icon ok">✓</span><div><b>Database</b><small>D1 auto-provision</small></div></div><div class="env-item"><span class="diag-icon ok">✓</span><div><b>Realtime</b><small>Durable Objects WebSocket</small></div></div><div class="env-item"><span class="diag-icon ok">✓</span><div><b>Storage</b><small>R2</small></div></div></div><form method="post">${csrfField(s)}<label>Nama Admin<input name="name" required autocomplete="name"></label><label>Email Admin<input type="email" name="email" required autocomplete="email"></label><label>Password Admin<input type="password" name="password" required minlength="10" autocomplete="new-password"></label><button class="btn primary full">Install Sekarang</button></form></div>`;
  return render(req,env,s,null,'Install',body,false);
}

async function homePage(req,env,s){return render(req,env,s,null,'Live Chat Telegram','<section class="hero"><span class="pill">CLOUDFLARE NATIVE • LIVE CHAT • TELEGRAM • MULTI-TENANT</span><h1>Satu pusat kendali live chat website dan Telegram.</h1><p>Realtime WebSocket, dashboard mobile-first, bot terisolasi per domain, Telegram OTP, traffic analytics, role, subscription, audit keamanan, dan diagnosis.</p><div class="hero-actions"><a class="btn primary" href="/register">Mulai</a><a class="btn ghost" href="/login">Login</a></div></section>',false);}

async function registerPage(req,env,ctx,s,user){
  if(user)return redirect('/dashboard');let err='';
  if(req.method==='POST'){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else try{if(!await authBot(env))throw new Error('Bot autentikasi belum dikonfigurasi oleh admin.');const r=await register(env,ctx,req,b);s.data.register_uid=r.user_id;s.data.register_link=r.token;s.dirty=true;return redirect(`/telegram/connect?token=${encodeURIComponent(r.token)}`);}catch(x){err=x.message;}}
  const body=`<div class="auth-card"><h1>Buat akun</h1><p class="muted">Telegram dipakai sebagai faktor verifikasi akun.</p>${err?`<div class="alert error">${e(err)}</div>`:''}<form method="post">${csrfField(s)}<label>Nama<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Username Telegram<input name="telegram" placeholder="@username" required></label><label>Password<input type="password" name="password" minlength="10" required></label><button class="btn primary full">Daftar & Hubungkan Telegram</button></form><p class="auth-foot">Sudah punya akun? <a href="/login">Login</a></p></div>`;return render(req,env,s,null,'Register',body,false);
}

async function telegramConnectPage(req,env,s,url){
  const token=url.searchParams.get('token')||s.data.register_link||'';const link=token?await one(env,'SELECT tl.*,u.telegram_verified_at,u.telegram_username FROM telegram_links tl JOIN users u ON u.id=tl.user_id WHERE tl.token=?',[token]):null;if(!link)return redirect('/register');const bot=await authBot(env);const username=String(bot?.username||'').replace(/^@/,'');if(!username)return render(req,env,s,null,'Telegram Verification','<div class="auth-card"><h1>Hubungkan Telegram</h1><div class="alert error">Bot autentikasi belum siap. Hubungi administrator.</div></div>',false);
  const httpsDeep=`https://t.me/${encodeURIComponent(username)}?start=${encodeURIComponent(token)}`,appDeep=`tg://resolve?domain=${encodeURIComponent(username)}&start=${encodeURIComponent(token)}`,paired=!!link.telegram_verified_at;
  const linkOnly=link.purpose==='link_only';const body=`<div class="auth-card"><div class="status-orb ${paired?'ok':'wait'}"></div><h1>Hubungkan Telegram</h1><p class="muted">Tekan tombol di bawah. Sistem mencoba aplikasi Telegram lebih dulu, lalu fallback ke t.me. Tekan <b>Start</b>. ${linkOnly?'Setelah pairing akun langsung terhubung.':'Setelah pairing, OTP dikirim otomatis.'}</p><a id="openTelegramApp" class="btn primary full" href="${attr(appDeep)}" data-app="${attr(appDeep)}" data-fallback="${attr(httpsDeep)}">Buka Bot Telegram</a><p class="auth-foot">Aplikasi tidak terbuka? <a target="_blank" rel="noopener" href="${attr(httpsDeep)}">Buka lewat t.me</a></p><div id="pairStatus" data-token="${attr(token)}" data-link-only="${linkOnly?'1':'0'}" class="pair-status">${paired?(linkOnly?'Telegram terhubung ✓':'Telegram terhubung. Masukkan OTP.'):'Menunggu pairing Telegram…'}</div>${linkOnly?(paired?'<a class="btn primary full" href="/admin/settings">Kembali ke Admin</a>':''):`<form method="post" action="/register/verify">${csrfField(s)}<input type="hidden" name="uid" value="${Number(link.user_id)}"><input type="hidden" name="token" value="${attr(token)}"><label>OTP 6 digit<input inputmode="numeric" pattern="[0-9]{6}" maxlength="6" name="otp" required></label><button class="btn primary full">Verifikasi & Masuk</button></form>`}</div>`;return render(req,env,s,null,'Telegram Verification',body,false);
}

async function registerVerify(req,env,ctx,s){if(req.method!=='POST')return redirect('/register');const b=await form(req);if(!csrfOk(req,s,b)){flash(s,'error','CSRF tidak valid.');return redirect('/register');}const uid=Number(b.uid||0);if(await activateRegistration(env,ctx,req,s,uid,String(b.otp||'')))return redirect('/dashboard');flash(s,'error','OTP salah atau kedaluwarsa.');return redirect(`/telegram/connect?token=${encodeURIComponent(b.token||s.data.register_link||'')}`);}

async function loginPage(req,env,ctx,s,user){if(user)return redirect(user.role==='super_admin'?'/admin':'/dashboard');let err='';if(req.method==='POST'){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else try{await beginLogin(env,ctx,req,s,b.email,b.password);return redirect('/login/otp');}catch(x){err=x.message;}}return render(req,env,s,null,'Login',`<div class="auth-card"><h1>Login aman</h1><p class="muted">Password + OTP Telegram.</p>${err?`<div class="alert error">${e(err)}</div>`:''}<form method="post">${csrfField(s)}<label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" required></label><button class="btn primary full">Lanjut OTP</button></form><div class="auth-links"><a href="/register">Daftar</a><a href="/forgot">Lupa sandi</a></div></div>`,false);}

async function loginOtpPage(req,env,ctx,s){if(!s.data.pending_login)return redirect('/login');let err='';if(req.method==='POST'){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else if(await completeLogin(env,ctx,req,s,b.otp))return redirect('/dashboard');else err='OTP salah/kedaluwarsa.';}return render(req,env,s,null,'OTP Login',`<div class="auth-card"><h1>Verifikasi OTP</h1><p class="muted">Kode dikirim ke Telegram terverifikasi.</p>${err?`<div class="alert error">${e(err)}</div>`:''}<form method="post">${csrfField(s)}<label>OTP<input inputmode="numeric" maxlength="6" name="otp" required></label><button class="btn primary full">Masuk Dashboard</button></form></div>`,false);}

async function forgotPage(req,env,s){let msg='';if(req.method==='POST'){const b=await form(req);if(csrfOk(req,s,b)){const u=await one(env,'SELECT * FROM users WHERE email=?',[String(b.email||'').toLowerCase().trim()]);if(u?.telegram_chat_id){await issueOtp(env,u.id,'reset');s.data.reset_uid=u.id;s.dirty=true;}msg='Jika akun valid, OTP reset telah dikirim ke Telegram.';}}return render(req,env,s,null,'Lupa Sandi',`<div class="auth-card"><h1>Reset sandi</h1>${msg?`<div class="alert ok">${e(msg)}</div>`:''}<form method="post">${csrfField(s)}<label>Email akun<input type="email" name="email" required></label><button class="btn primary full">Kirim OTP Reset</button></form>${s.data.reset_uid?'<a class="btn ghost full" href="/reset">Masukkan OTP</a>':''}</div>`,false);}

async function resetPage(req,env,ctx,s){const uid=Number(s.data.reset_uid||0);if(!uid)return redirect('/forgot');let err='';if(req.method==='POST'){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else{const pe=validatePassword(String(b.password||''));if(pe)err=pe;else if(!await verifyOtp(env,uid,'reset',b.otp))err='OTP salah atau kedaluwarsa.';else{await run(env,'UPDATE users SET password_hash=? WHERE id=?',[await edgeHashPassword(env,b.password),uid]);delete s.data.reset_uid;s.dirty=true;const u=await one(env,'SELECT * FROM users WHERE id=?',[uid]);await audit(env,ctx,{event:'PASSWORD_RESET',risk:40,tenantId:u?.tenant_id,userId:uid,request:req});flash(s,'ok','Password berhasil diubah.');return redirect('/login');}}}return render(req,env,s,null,'Reset Password',`<div class="auth-card"><h1>Password baru</h1>${err?`<div class="alert error">${e(err)}</div>`:''}<form method="post">${csrfField(s)}<label>OTP Telegram<input name="otp" maxlength="6" inputmode="numeric" required></label><label>Password baru<input type="password" name="password" minlength="10" required></label><button class="btn primary full">Simpan Password</button></form></div>`,false);}

async function joinPage(req,env,ctx,s,user,url){
  if(user)return redirect('/dashboard');const token=url.searchParams.get('token')||'';const link=token?await one(env,"SELECT tl.*,u.name,u.email,u.status,u.role,u.telegram_username FROM telegram_links tl JOIN users u ON u.id=tl.user_id WHERE tl.token=? AND tl.expires_at>?",[token,nowIso()]):null;if(!link||link.role!=='member')return render(req,env,s,null,'Undangan Team','<div class="auth-card"><h1>Undangan tidak valid</h1><p class="muted">Link mungkin kedaluwarsa atau sudah dipakai.</p><a class="btn ghost full" href="/login">Kembali</a></div>',false);
  let err='';if(req.method==='POST'){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else{const pe=validatePassword(String(b.password||''));if(pe)err=pe;else{await run(env,'UPDATE users SET password_hash=? WHERE id=?',[await edgeHashPassword(env,b.password),link.user_id]);s.data.register_uid=Number(link.user_id);s.data.register_link=token;s.dirty=true;return redirect(`/telegram/connect?token=${encodeURIComponent(token)}`);}}}
  return render(req,env,s,null,'Aktivasi Team',`<div class="auth-card"><h1>Aktifkan akun team</h1><p class="muted">${e(link.name)} • ${e(link.email)}</p>${err?`<div class="alert error">${e(err)}</div>`:''}<form method="post">${csrfField(s)}<label>Buat password<input type="password" name="password" minlength="10" required></label><button class="btn primary full">Lanjut Hubungkan Telegram</button></form></div>`,false);
}

async function tenantStats(env,tid){
  const cutoff=new Date(Date.now()-90000).toISOString().replace('T',' ').replace('Z','').slice(0,19),today=new Date().toISOString().slice(0,10)+' 00:00:00';
  const [online,open,views,domains,total]=await Promise.all([
    one(env,'SELECT COUNT(*) c FROM visitors v JOIN domains d ON d.id=v.domain_id WHERE d.tenant_id=? AND v.last_seen_at>=?',[tid,cutoff]),
    one(env,"SELECT COUNT(*) c FROM chats c JOIN domains d ON d.id=c.domain_id WHERE d.tenant_id=? AND c.status='open'",[tid]),
    one(env,'SELECT COUNT(*) c FROM pageviews p JOIN domains d ON d.id=p.domain_id WHERE d.tenant_id=? AND p.created_at>=?',[tid,today]),
    one(env,"SELECT COUNT(*) c FROM domains WHERE tenant_id=? AND status='active'",[tid]),
    one(env,'SELECT COUNT(*) c FROM chats c JOIN domains d ON d.id=c.domain_id WHERE d.tenant_id=?',[tid])
  ]);
  const hourly=[];for(let i=23;i>=0;i--){const a=new Date(Date.now()-i*3600000);a.setUTCMinutes(0,0,0);const b=new Date(a.getTime()+3600000);const c=await one(env,'SELECT COUNT(*) c FROM pageviews p JOIN domains d ON d.id=p.domain_id WHERE d.tenant_id=? AND p.created_at>=? AND p.created_at<?',[tid,a.toISOString().replace('T',' ').replace('Z','').slice(0,19),b.toISOString().replace('T',' ').replace('Z','').slice(0,19)]);hourly.push(Number(c?.c||0));}
  return {online:Number(online?.c||0),open_chats:Number(open?.c||0),views_today:Number(views?.c||0),domains:Number(domains?.c||0),all_chats:Number(total?.c||0),hourly};
}
function stat(label,value,icon){const x={pulse:'◉',chat:'◇',trend:'↗',domain:'⌁',user:'◎'}[icon]||'•';return `<div class="stat-card"><span class="stat-icon">${x}</span><div><strong>${e(value)}</strong><small>${e(label)}</small></div></div>`;}

async function dashboardPage(req,env,s,user){
  if(user.role==='super_admin')return redirect('/admin');const tid=user.tenant_id,stats=await tenantStats(env,tid),plan=await currentPlan(env,tid);const recent=await all(env,'SELECT c.*,d.domain FROM chats c JOIN domains d ON d.id=c.domain_id WHERE d.tenant_id=? ORDER BY c.id DESC LIMIT 6',[tid]);const rows=recent.map(c=>`<a class="list-row" href="/inbox?chat=${c.id}"><div><b>${e(c.name||`Visitor ${c.code}`)}</b><small>${e(c.domain)}</small></div><span class="badge ${e(c.status)}">${e(c.status)}</span></a>`).join('')||'<div class="empty">Belum ada chat.</div>';
  const body=`<div class="page-head"><div><span class="eyebrow">CONTROL CENTER • CLOUDFLARE EDGE</span><h1>Selamat datang, ${e(user.name)}</h1></div><div class="plan-chip">${e(plan?.name||'No plan')} • ${e(plan?.subscription_status||'-')}</div></div><div class="stats">${stat('Pengunjung online',stats.online,'pulse')}${stat('Chat aktif',stats.open_chats,'chat')}${stat('Hari ini',stats.views_today,'trend')}${stat('Domain aktif',stats.domains,'domain')}</div><div class="grid-2"><section class="panel"><div class="panel-head"><h2>Live pulse</h2><a href="/analytics">Analytics</a></div><div class="mini-chart" data-chart='${attr(JSON.stringify(stats.hourly))}'></div></section><section class="panel"><div class="panel-head"><h2>Chat terbaru</h2><a href="/inbox">Buka Inbox</a></div>${rows}</section></div><section class="panel quick"><h2>Quick actions</h2><div class="quick-grid"><a href="/domains">＋ Domain</a><a href="/bots">🤖 Bot Telegram</a><a href="/widget">◈ Widget</a><a href="/diagnostics">⌁ Diagnosis</a></div></section>`;return render(req,env,s,user,'Dashboard',body,true);
}

async function inboxPage(req,env,s,user,url){
  if(!await can(env,user,'view_chat'))return forbidden();const tid=user.tenant_id,chats=await all(env,'SELECT c.*,d.domain FROM chats c JOIN domains d ON d.id=c.domain_id WHERE d.tenant_id=? ORDER BY c.updated_at DESC LIMIT 100',[tid]);const selected=Number(url.searchParams.get('chat')||chats[0]?.id||0);const chat=selected?await one(env,'SELECT c.*,d.domain,d.id domain_id FROM chats c JOIN domains d ON d.id=c.domain_id WHERE c.id=? AND d.tenant_id=?',[selected,tid]):null;const items=chats.map(c=>`<a class="chat-item ${selected===Number(c.id)?'active':''}" href="/inbox?chat=${c.id}"><span class="avatar">${e((c.name||'V').slice(0,1).toUpperCase())}</span><div><b>${e(c.name||c.code)}</b><small>${e(c.domain)} • ${e(c.status)}</small></div></a>`).join('');let msgs='',last=0;if(chat){const mm=await all(env,'SELECT * FROM messages WHERE chat_id=? ORDER BY id ASC LIMIT 300',[selected]);for(const m of mm){last=Math.max(last,Number(m.id));msgs+=`<div class="bubble ${m.sender_type==='visitor'?'visitor':'agent'}"><span>${e(m.body).replace(/\n/g,'<br>')}</span><small>${e(String(m.created_at).slice(11,16))}</small></div>`;}}
  const qr=(await all(env,'SELECT * FROM quick_replies WHERE tenant_id=? ORDER BY shortcut LIMIT 20',[tid])).map(q=>`<button type="button" class="chip quick-reply" data-reply="${attr(q.body)}">/${e(q.shortcut)}</button>`).join('');
  const body=`<div class="inbox-layout"><aside class="chat-list"><div class="panel-head"><h2>Inbox</h2><span class="badge">${chats.length}</span></div>${items}</aside><section class="conversation">${chat?`<div class="conv-head"><div><b>${e(chat.name||chat.code)}</b><small>${e(chat.domain)} • ${e(chat.status)}</small></div></div><div id="messageStream" data-chat="${selected}" data-domain="${chat.domain_id}" data-last="${last}" class="messages">${msgs}</div>${qr?`<div class="chips reply-chips">${qr}</div>`:''}<form id="dashboardReply" class="reply-box">${csrfField(s)}<input type="hidden" name="chat_id" value="${selected}"><textarea name="body" placeholder="Tulis balasan…" required></textarea><button class="btn primary">Kirim</button></form>`:'<div class="empty center">Pilih percakapan.</div>'}</section></div>`;return render(req,env,s,user,'Live Chat Inbox',body,true);
}

async function domainsPage(req,env,ctx,s,user){
  if(!await can(env,user,'manage_domain'))return forbidden();const tid=user.tenant_id;let err='';if(req.method==='POST'){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else try{if(b.action==='add'){if(!await allowResource(env,tid,'domains'))throw new Error('Limit domain paket tercapai.');const domain=normalizeDomain(b.domain);if(!domain)throw new Error('Domain tidak valid.');const key='site_pk_'+randomToken(18),verify='jlc_'+randomToken(18),id=await insert(env,"INSERT INTO domains(tenant_id,domain,public_key,verify_token,status,created_at) VALUES(?,?,?,?, 'pending',?)",[tid,domain,key,verify,nowIso()]);await run(env,'INSERT INTO widget_settings(domain_id,updated_at) VALUES(?,?)',[id,nowIso()]);await audit(env,ctx,{event:'DOMAIN_ADD',risk:20,metadata:{domain},tenantId:tid,userId:user.id,request:req});}else if(b.action==='verify'){await verifyDomain(env,tid,Number(b.id));await audit(env,ctx,{event:'DOMAIN_VERIFIED',risk:5,metadata:{id:Number(b.id)},tenantId:tid,userId:user.id,request:req});}else if(b.action==='delete'){await run(env,'DELETE FROM domains WHERE id=? AND tenant_id=?',[Number(b.id),tid]);await audit(env,ctx,{event:'DOMAIN_REMOVE',risk:30,metadata:{id:Number(b.id)},tenantId:tid,userId:user.id,request:req});}return redirect('/domains');}catch(x){err=x.message;}}
  const ds=await all(env,'SELECT * FROM domains WHERE tenant_id=? ORDER BY id DESC',[tid]),origin=baseUrl(req);const rows=ds.map(d=>{const script=`<script src="${origin}/widget.js" data-site="${d.public_key}" async></script>`;return `<div class="domain-card"><div class="domain-top"><div><b>${e(d.domain)}</b><small>${e(d.public_key)}</small></div><span class="badge ${e(d.status)}">${e(d.status)}</span></div><code class="codebox">${e(script)}</code><div class="card-actions"><form method="post">${csrfField(s)}<input type="hidden" name="action" value="verify"><input type="hidden" name="id" value="${d.id}"><button class="btn small">Verifikasi</button></form><button class="btn small ghost copy" data-copy="${attr(script)}">Copy Script</button><form method="post" onsubmit="return confirm('Hapus domain?')">${csrfField(s)}<input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="${d.id}"><button class="btn small danger">Hapus</button></form></div><details><summary>Cara verifikasi</summary><p>Pasang file <code>/.well-known/jopuja-live-connect.txt</code> dengan isi:</p><code class="codebox">${e(d.verify_token)}</code><p>Atau meta tag:</p><code class="codebox">${e(`<meta name="jopuja-live-connect" content="${d.verify_token}">`)}</code></details></div>`}).join('');
  return render(req,env,s,user,'Domains',`<div class="page-head"><div><span class="eyebrow">CONNECTION</span><h1>Domain</h1></div></div>${err?`<div class="alert error">${e(err)}</div>`:''}<section class="panel"><form method="post" class="inline-form">${csrfField(s)}<input type="hidden" name="action" value="add"><label>Tambah domain<input name="domain" placeholder="example.com" required></label><button class="btn primary">Tambah</button></form></section><div class="cards">${rows}</div>`,true);
}

async function verifyDomain(env,tid,id){const d=await one(env,'SELECT * FROM domains WHERE id=? AND tenant_id=?',[id,tid]);if(!d)throw new Error('Domain tidak ditemukan.');let ok=false;try{const f=await fetch(`https://${d.domain}/.well-known/jopuja-live-connect.txt`,{headers:{'user-agent':'JopujaLiveConnect/2.0'}});if(f.ok&&(await f.text()).trim()===d.verify_token)ok=true;}catch{}if(!ok)try{const r=await fetch(`https://${d.domain}/`,{headers:{'user-agent':'JopujaLiveConnect/2.0'}});const raw=(await r.text()).slice(0,300000);const needle1=`name="jopuja-live-connect"`,needle2=`content="${d.verify_token}"`;if(r.ok&&raw.includes(needle1)&&raw.includes(needle2))ok=true;}catch{}if(!ok)throw new Error('Token verifikasi belum ditemukan di domain.');await run(env,"UPDATE domains SET status='active',verified_at=? WHERE id=?",[nowIso(),id]);}

async function botsPage(req,env,ctx,s,user){
  if(!await can(env,user,'manage_bot'))return forbidden();const tid=user.tenant_id;let err='';
  if(req.method==='POST'){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else try{
    if(b.action==='add'){
      if(!await allowResource(env,tid,'bots'))throw new Error('Limit bot paket tercapai.');const token=normalizeToken(b.token),test=await tgCall(token,'getMe');if(!test.ok)throw new Error(`Token bot Telegram tidak valid: ${test.description||'unknown'}`);const username=test.result?.username||'',secret=secretToken(36),bind=randomToken(18);const id=await insert(env,"INSERT INTO bots(tenant_id,name,kind,token_enc,bot_username,notification_chat_id,bind_token,webhook_secret,status,created_at) VALUES(?,?, 'livechat',?,?,?,?,?,'active',?)",[tid,cap(b.name,120),await vaultEncrypt(env,token),username,String(b.chat_id||''),bind,secret,nowIso()]);const wh=await tgCall(token,'setWebhook',{url:`${baseUrl(req)}/webhook/bot/${id}/${secret}`,secret_token:secret,drop_pending_updates:true,allowed_updates:['message']});if(!wh.ok){await run(env,'DELETE FROM bots WHERE id=?',[id]);throw new Error(`Webhook bot gagal: ${wh.description||'unknown'}`);}await audit(env,ctx,{event:'BOT_ADD',risk:30,metadata:{bot_id:id,username},tenantId:tid,userId:user.id,request:req});
    }else if(b.action==='map'){
      const domain=await one(env,'SELECT id FROM domains WHERE id=? AND tenant_id=?',[Number(b.domain_id),tid]),bot=await one(env,'SELECT id FROM bots WHERE id=? AND tenant_id=?',[Number(b.bot_id),tid]);if(!domain||!bot)throw new Error('Domain/bot tidak valid.');const collision=await one(env,'SELECT domain_id FROM domain_bots WHERE bot_id=? AND domain_id<>?',[bot.id,domain.id]);if(collision)throw new Error('Bot ini sudah dipakai domain lain. Satu domain wajib satu bot berbeda.');await run(env,'INSERT INTO domain_bots(domain_id,bot_id) VALUES(?,?) ON CONFLICT(domain_id) DO UPDATE SET bot_id=excluded.bot_id',[domain.id,bot.id]);await audit(env,ctx,{event:'BOT_DOMAIN_MAP',risk:20,metadata:{domain_id:domain.id,bot_id:bot.id},tenantId:tid,userId:user.id,request:req});
    }else if(b.action==='delete'){
      const bot=await one(env,'SELECT * FROM bots WHERE id=? AND tenant_id=?',[Number(b.id),tid]);if(bot){try{await tgCall(await vaultDecrypt(env,bot.token_enc),'deleteWebhook',{drop_pending_updates:true});}catch{}await run(env,'DELETE FROM bots WHERE id=? AND tenant_id=?',[bot.id,tid]);await audit(env,ctx,{event:'BOT_REMOVE',risk:40,metadata:{bot_id:bot.id},tenantId:tid,userId:user.id,request:req});}
    }return redirect('/bots');
  }catch(x){err=x.message;}}
  const bots=await all(env,'SELECT * FROM bots WHERE tenant_id=? ORDER BY id DESC',[tid]),domains=await all(env,'SELECT d.*,db.bot_id FROM domains d LEFT JOIN domain_bots db ON db.domain_id=d.id WHERE d.tenant_id=?',[tid]);
  const cards=bots.map(b=>{const deep=b.bot_username?`https://t.me/${b.bot_username}?start=bind_${b.bind_token}`:'#';return `<div class="domain-card"><div class="domain-top"><div><b>🤖 ${e(b.name)}</b><small>@${e(b.bot_username)}</small></div><span class="badge ${b.notification_chat_id?'active':'pending'}">${b.notification_chat_id?'ready':'pairing'}</span></div><p class="muted">Chat ID tujuan: ${e(b.notification_chat_id||'belum terhubung')}</p>${b.notification_chat_id?'':`<a class="btn small primary" target="_blank" rel="noopener" href="${attr(deep)}">Hubungkan Bot ke Telegram</a>`}<form method="post" onsubmit="return confirm('Hapus bot?')">${csrfField(s)}<input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="${b.id}"><button class="btn small danger">Hapus</button></form></div>`}).join('');
  const opts=bots.map(b=>`<option value="${b.id}">${e(b.name)} @${e(b.bot_username)}</option>`).join(''),dopts=domains.map(d=>`<option value="${d.id}">${e(d.domain)}${d.bot_id?' • mapped':''}</option>`).join('');
  return render(req,env,s,user,'Telegram Bots',`<div class="page-head"><div><span class="eyebrow">TELEGRAM ROUTER • CLOUDFLARE</span><h1>Bot Telegram</h1></div></div>${err?`<div class="alert error">${e(err)}</div>`:''}<div class="grid-2"><section class="panel"><h2>Tambah bot live chat</h2><p class="muted">Chat ID boleh dikosongkan. Setelah bot dibuat, tekan tombol Hubungkan Bot dan Start di Telegram.</p><form method="post">${csrfField(s)}<input type="hidden" name="action" value="add"><label>Nama bot<input name="name" required></label><label>Bot token<input type="password" name="token" required autocomplete="off"></label><label>Chat ID tujuan (opsional)<input name="chat_id" placeholder="otomatis via pairing"></label><button class="btn primary">Validasi & Pasang Webhook</button></form></section><section class="panel"><h2>Hubungkan bot ke domain</h2><form method="post">${csrfField(s)}<input type="hidden" name="action" value="map"><label>Domain<select name="domain_id">${dopts}</select></label><label>Bot<select name="bot_id">${opts}</select></label><button class="btn primary">Simpan Routing</button></form></section></div><div class="cards">${cards}</div>`,true);
}

async function widgetPage(req,env,ctx,s,user,url){
  if(!await can(env,user,'manage_widget'))return forbidden();const tid=user.tenant_id,domains=await all(env,'SELECT * FROM domains WHERE tenant_id=? ORDER BY domain',[tid]),did=Number(url.searchParams.get('domain')||domains[0]?.id||0),d=did?await one(env,'SELECT * FROM domains WHERE id=? AND tenant_id=?',[did,tid]):null;let w=d?await one(env,'SELECT * FROM widget_settings WHERE domain_id=?',[did]):null;let err='';
  if(req.method==='POST'&&d){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else try{let iconKey=w?.custom_icon_key||null;const f=b.custom_icon;if(f&&typeof f==='object'&&Number(f.size)>0){if(f.size>1024*1024)throw new Error('Ikon custom maksimal 1 MB.');if(!['image/png','image/jpeg','image/webp','image/svg+xml'].includes(f.type))throw new Error('Ikon wajib PNG/JPG/WEBP/SVG.');const key=`widget-icons/t${tid}/d${did}/${randomToken(18)}.${mimeExt(f.type)}`;await env.UPLOADS.put(key,f.stream(),{httpMetadata:{contentType:f.type}});await insert(env,"INSERT INTO media_assets(tenant_id,user_id,domain_id,kind,r2_key,mime,size,created_at) VALUES(?,?,?,'widget_icon',?,?,?,?)",[tid,user.id,did,key,f.type,f.size,nowIso()]);if(iconKey)await env.UPLOADS.delete(iconKey).catch(()=>{});iconKey=key;}await run(env,'UPDATE widget_settings SET title=?,welcome=?,position=?,theme=?,accent=?,icon=?,custom_icon_key=?,require_name=?,require_phone=?,require_email=?,offline_message=?,launcher_label=?,business_hours_json=?,updated_at=? WHERE domain_id=?',[cap(b.title,100),cap(b.welcome,700),['left','right'].includes(b.position)?b.position:'right',['auto','dark','light'].includes(b.theme)?b.theme:'auto',sanitizeColor(b.accent),['chat','support','telegram','custom'].includes(b.icon)?b.icon:'chat',iconKey,b.require_name?1:0,b.require_phone?1:0,b.require_email?1:0,cap(b.offline_message,700),cap(b.launcher_label,40),JSON.stringify({timezone:b.timezone||'Asia/Jakarta',mon:b.mon||'',tue:b.tue||'',wed:b.wed||'',thu:b.thu||'',fri:b.fri||'',sat:b.sat||'',sun:b.sun||''}),nowIso(),did]);await audit(env,ctx,{event:'WIDGET_CHANGED',risk:10,metadata:{domain_id:did},tenantId:tid,userId:user.id,request:req});flash(s,'ok','Widget diperbarui.');return redirect(`/widget?domain=${did}`);}catch(x){err=x.message;}}
  if(d)w=await one(env,'SELECT * FROM widget_settings WHERE domain_id=?',[did]);let hours={};try{hours=JSON.parse(w?.business_hours_json||'{}')}catch{}
  const tabs=domains.map(x=>`<a class="chip ${did===Number(x.id)?'selected':''}" href="/widget?domain=${x.id}">${e(x.domain)}</a>`).join('');
  const formHtml=w?`<form method="post" enctype="multipart/form-data" class="widget-form">${csrfField(s)}<label>Judul<input name="title" value="${attr(w.title)}"></label><label>Pesan pembuka<textarea name="welcome">${e(w.welcome)}</textarea></label><div class="form-grid"><label>Posisi<select name="position"><option value="right"${selected(w.position,'right')}>right</option><option value="left"${selected(w.position,'left')}>left</option></select></label><label>Mode<select name="theme"><option value="auto"${selected(w.theme,'auto')}>auto</option><option value="dark"${selected(w.theme,'dark')}>dark</option><option value="light"${selected(w.theme,'light')}>light</option></select></label><label>Accent<input type="color" name="accent" value="${attr(w.accent)}"></label><label>Ikon<select name="icon"><option value="chat"${selected(w.icon,'chat')}>Chat</option><option value="support"${selected(w.icon,'support')}>Support</option><option value="telegram"${selected(w.icon,'telegram')}>Telegram</option><option value="custom"${selected(w.icon,'custom')}>Custom R2</option></select></label></div><label>Upload ikon custom (opsional)<input type="file" name="custom_icon" accept="image/png,image/jpeg,image/webp,image/svg+xml"></label><label>Label FAB (opsional)<input name="launcher_label" value="${attr(w.launcher_label||'')}" placeholder="Chat sekarang"></label><label class="switch-row"><input type="checkbox" name="require_name" value="1"${checked(w.require_name)}> Wajib nama</label><label class="switch-row"><input type="checkbox" name="require_phone" value="1"${checked(w.require_phone)}> Wajib nomor telepon</label><label class="switch-row"><input type="checkbox" name="require_email" value="1"${checked(w.require_email)}> Wajib email</label><label>Pesan offline<textarea name="offline_message">${e(w.offline_message)}</textarea></label><h3>Jam Operasional</h3><label>Timezone<input name="timezone" value="${attr(hours.timezone||'Asia/Jakarta')}"></label><div class="form-grid">${['mon','tue','wed','thu','fri','sat','sun'].map(k=>`<label>${k.toUpperCase()}<input name="${k}" value="${attr(hours[k]||'')}" placeholder="09:00-18:00"></label>`).join('')}</div><button class="btn primary">Simpan Tampilan</button></form>`:'<div class="empty">Tambahkan domain dulu.</div>';
  const preview=w?`<div class="preview-phone"><div class="fake-site"><div class="fake-nav"></div><div class="fake-hero"></div><div class="fake-lines"></div></div><div class="preview-widget ${e(w.position)}" style="--accent:${attr(w.accent)}"><div class="preview-panel"><b>${e(w.title)}</b><p>${e(w.welcome)}</p><div class="preview-input">Tulis pesan…</div></div><div class="preview-fab">◈</div></div></div>`:'';
  return render(req,env,s,user,'Widget Designer',`<div class="page-head"><div><span class="eyebrow">WIDGET DESIGNER</span><h1>Tampilan Live Chat</h1></div></div>${err?`<div class="alert error">${e(err)}</div>`:''}<div class="chips">${tabs}</div><div class="grid-2"><section class="panel">${formHtml}</section><section class="panel"><h2>Live preview</h2>${preview}</section></div>`,true);
}

async function teamPage(req,env,ctx,s,user){
  if(!await can(env,user,'manage_team'))return forbidden();const tid=user.tenant_id;let err='',invite='';if(req.method==='POST'){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else try{if(!await allowResource(env,tid,'agents'))throw new Error('Limit anggota paket tercapai.');const email=String(b.email||'').trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw new Error('Email tidak valid.');const role=['agent','supervisor','admin','viewer'].includes(b.role)?b.role:'agent';let member=await one(env,'SELECT * FROM users WHERE email=?',[email]);if(member&&Number(member.tenant_id)!==Number(tid))throw new Error('Email sudah menjadi bagian tenant lain.');if(!member){const temp=randomToken(20)+'Aa1',uid=await insert(env,"INSERT INTO users(tenant_id,name,email,password_hash,role,status,telegram_username,created_at) VALUES(?,?,?,?, 'member','pending',?,?)",[tid,cap(b.name,120),email,await edgeHashPassword(env,temp),String(b.telegram||'').replace(/^@/,''),nowIso()]);await run(env,"INSERT INTO user_preferences(user_id,theme,sound,notifications_json,updated_at) VALUES(?,'system','soft','{}',?)",[uid,nowIso()]);member=await one(env,'SELECT * FROM users WHERE id=?',[uid]);}const custom={reply_chat:role!=='viewer',view_analytics:['viewer','supervisor','admin'].includes(role)};await run(env,'INSERT INTO team_members(tenant_id,user_id,team_role,permissions_json,created_at) VALUES(?,?,?,?,?) ON CONFLICT(tenant_id,user_id) DO UPDATE SET team_role=excluded.team_role,permissions_json=excluded.permissions_json',[tid,member.id,role,JSON.stringify(custom),nowIso()]);if(member.status!=='active'){const token=randomToken(40).slice(0,60);await run(env,"INSERT INTO telegram_links(user_id,token,purpose,expires_at,created_at) VALUES(?,?,'team',?,?)",[member.id,token,isoAfter(1800),nowIso()]);invite=`${baseUrl(req)}/join?token=${token}`;}await audit(env,ctx,{event:'TEAM_MEMBER_ADD',risk:25,metadata:{email,role},tenantId:tid,userId:user.id,request:req});}catch(x){err=x.message;}}
  const members=await all(env,'SELECT tm.*,u.name,u.email,u.status FROM team_members tm JOIN users u ON u.id=tm.user_id WHERE tm.tenant_id=? ORDER BY tm.id DESC',[tid]),rows=members.map(x=>`<div class="list-row"><div><b>${e(x.name)}</b><small>${e(x.email)} • ${e(x.status)}</small></div><span class="badge">${e(x.team_role)}</span></div>`).join('')||'<div class="empty">Belum ada anggota.</div>',inviteBox=invite?`<div class="alert ok"><b>Link aktivasi dibuat.</b><code class="codebox">${e(invite)}</code><button class="btn small copy" data-copy="${attr(invite)}">Copy Link</button><p>Link berlaku 30 menit. User membuat password lalu pairing Telegram + OTP.</p></div>`:'';
  return render(req,env,s,user,'Team',`<div class="page-head"><div><span class="eyebrow">ACCESS CONTROL</span><h1>Team & Role</h1></div></div>${err?`<div class="alert error">${e(err)}</div>`:''}${inviteBox}<div class="grid-2"><section class="panel"><h2>Tambah anggota</h2><form method="post">${csrfField(s)}<label>Nama<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Username Telegram<input name="telegram" placeholder="@username" required></label><label>Role<select name="role"><option>agent</option><option>supervisor</option><option>admin</option><option>viewer</option></select></label><button class="btn primary">Buat Undangan</button></form></section><section class="panel"><h2>Anggota</h2>${rows}</section></div>`,true);
}

async function analyticsPage(req,env,s,user){if(!await can(env,user,'view_analytics'))return forbidden();const tid=user.tenant_id,stats=await tenantStats(env,tid),top=await all(env,'SELECT pv.url,COUNT(*) c FROM pageviews pv JOIN domains d ON d.id=pv.domain_id WHERE d.tenant_id=? GROUP BY pv.url ORDER BY c DESC LIMIT 10',[tid]),rows=top.map(x=>`<div class="metric-row"><span>${e(x.url)}</span><b>${Number(x.c)}</b></div>`).join('');return render(req,env,s,user,'Analytics',`<div class="page-head"><div><span class="eyebrow">REALTIME DATA • CLOUDFLARE</span><h1>Traffic Analytics</h1></div></div><div class="stats">${stat('Online',stats.online,'pulse')}${stat('Pageviews hari ini',stats.views_today,'trend')}${stat('Open chat',stats.open_chats,'chat')}${stat('Total chat',stats.all_chats,'chat')}</div><div class="grid-2"><section class="panel"><h2>24 jam terakhir</h2><div class="big-chart mini-chart" data-chart='${attr(JSON.stringify(stats.hourly))}'></div></section><section class="panel"><h2>Halaman teratas</h2>${rows||'<div class="empty">Belum ada data.</div>'}</section></div>`,true);}

async function visitorsPage(req,env,s,user){if(!await can(env,user,'view_analytics'))return forbidden();const tid=user.tenant_id,cutoff=new Date(Date.now()-90000).toISOString().replace('T',' ').replace('Z','').slice(0,19),vs=await all(env,'SELECT v.*,d.domain FROM visitors v JOIN domains d ON d.id=v.domain_id WHERE d.tenant_id=? ORDER BY v.last_seen_at DESC LIMIT 250',[tid]),rows=vs.map(v=>{const online=v.last_seen_at>=cutoff;return `<div class="visitor-row"><span class="presence ${online?'online':'offline'}"></span><div><b>${e(v.domain)}</b><small>${e(v.last_url||'/')}</small></div><div class="visitor-meta"><span>${e(String(v.user_agent||'Unknown').slice(0,38))}</span><small>${e(v.country||'')} • ${e(v.last_seen_at)}</small></div></div>`}).join('');return render(req,env,s,user,'Live Visitors',`<div class="page-head"><div><span class="eyebrow">LIVE REPORT</span><h1>Pengunjung Realtime</h1></div></div><section class="panel"><div class="panel-head"><h2>Aktivitas terbaru</h2><span class="muted">Online = heartbeat ≤ 90 detik</span></div>${rows||'<div class="empty">Belum ada traffic.</div>'}</section>`,true);}

async function notificationsPage(req,env,ctx,s,user){if(!await can(env,user,'manage_notifications')&&user.role!=='owner')return forbidden();let pref=await one(env,'SELECT * FROM user_preferences WHERE user_id=?',[user.id]),err='';if(req.method==='POST'){
  const fd=await req.formData();const b=Object.fromEntries(fd.entries());if(!csrfOk(req,s,b))err='CSRF tidak valid.';else try{let asset=pref?.sound_asset_key||null;const file=fd.get('sound_file');if(file&&typeof file==='object'&&Number(file.size)>0){if(file.size>2*1024*1024)throw new Error('File nada maksimal 2 MB.');if(!['audio/mpeg','audio/ogg','audio/wav','audio/x-wav','audio/mp4'].includes(file.type))throw new Error('Format nada harus MP3/OGG/WAV/M4A.');const key=`sounds/u${user.id}/${randomToken(18)}.${mimeExt(file.type)}`;await env.UPLOADS.put(key,file.stream(),{httpMetadata:{contentType:file.type}});await insert(env,'INSERT INTO media_assets(tenant_id,user_id,kind,r2_key,mime,size,created_at) VALUES(?,?,\'sound\',?,?,?,?)',[user.tenant_id,user.id,key,file.type,file.size,nowIso()]);if(asset)await env.UPLOADS.delete(asset).catch(()=>{});asset=key;}const notifications={new_chat:!!b.new_chat,visitor_online:!!b.visitor_online,security:!!b.security};await run(env,'UPDATE user_preferences SET sound=?,sound_asset_key=?,notifications_json=?,updated_at=? WHERE user_id=?',[['soft','crisp','digital','custom','none'].includes(b.sound)?b.sound:'soft',asset,JSON.stringify(notifications),nowIso(),user.id]);await audit(env,ctx,{event:'NOTIFICATION_SETTINGS_CHANGED',risk:5,tenantId:user.tenant_id,userId:user.id,request:req});flash(s,'ok','Pengaturan notifikasi disimpan.');return redirect('/notifications');}catch(x){err=x.message;}}
  pref=await one(env,'SELECT * FROM user_preferences WHERE user_id=?',[user.id]);let n={};try{n=JSON.parse(pref.notifications_json||'{}')}catch{}const body=`<div class="page-head"><div><span class="eyebrow">PERSONAL ALERT</span><h1>Nada & Notifikasi</h1></div></div>${err?`<div class="alert error">${e(err)}</div>`:''}<div class="grid-2"><section class="panel"><form method="post" enctype="multipart/form-data">${csrfField(s)}<label>Profil suara<select name="sound"><option value="soft"${selected(pref.sound,'soft')}>Soft</option><option value="crisp"${selected(pref.sound,'crisp')}>Crisp</option><option value="digital"${selected(pref.sound,'digital')}>Digital</option><option value="custom"${selected(pref.sound,'custom')}>Custom Upload</option><option value="none"${selected(pref.sound,'none')}>Off</option></select></label><label>Upload nada custom<input type="file" name="sound_file" accept="audio/*"></label><label class="switch-row"><input type="checkbox" name="new_chat" value="1" ${n.new_chat!==false?'checked':''}> Chat baru</label><label class="switch-row"><input type="checkbox" name="visitor_online" value="1" ${n.visitor_online?'checked':''}> Visitor baru</label><label class="switch-row"><input type="checkbox" name="security" value="1" ${n.security!==false?'checked':''}> Security alert</label><button class="btn primary">Simpan Notifikasi</button></form></section><section class="panel"><h2>Isolasi per user</h2><p class="muted">Setiap akun menyimpan profil nada sendiri. Custom audio disimpan private di Cloudflare R2 dan hanya dapat diakses setelah login.</p><button type="button" id="testSound" class="btn ghost">Test Nada</button></section></div>`;return render(req,env,s,user,'Notifications',body,true);
}
function mimeExt(m){return {'audio/mpeg':'mp3','audio/ogg':'ogg','audio/wav':'wav','audio/x-wav':'wav','audio/mp4':'m4a','image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/svg+xml':'svg'}[m]||'bin';}

async function automationPage(req,env,ctx,s,user){if(!await can(env,user,'manage_automation')&&user.role!=='owner')return forbidden();const tid=user.tenant_id;let err='';if(req.method==='POST'){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else try{if(b.action==='quick_add'){const shortcut=String(b.shortcut||'').trim().toLowerCase().replace(/[^a-z0-9_-]/g,'').slice(0,30);if(!shortcut||!b.body)throw new Error('Shortcut/body wajib.');await run(env,'INSERT INTO quick_replies(tenant_id,shortcut,body,created_at) VALUES(?,?,?,?) ON CONFLICT(tenant_id,shortcut) DO UPDATE SET body=excluded.body',[tid,shortcut,cap(b.body,3000),nowIso()]);}else if(b.action==='quick_delete')await run(env,'DELETE FROM quick_replies WHERE id=? AND tenant_id=?',[Number(b.id),tid]);else if(b.action==='rule_add'){await insert(env,'INSERT INTO automation_rules(tenant_id,name,event_type,action_type,action_json,enabled,created_at) VALUES(?,?,?,?,?,1,?)',[tid,cap(b.name,100),b.event_type,b.action_type,JSON.stringify({message:cap(b.message,1000)}),nowIso()]);}else if(b.action==='rule_delete')await run(env,'DELETE FROM automation_rules WHERE id=? AND tenant_id=?',[Number(b.id),tid]);await audit(env,ctx,{event:'AUTOMATION_CHANGED',risk:10,tenantId:tid,userId:user.id,request:req});return redirect('/automation');}catch(x){err=x.message;}}
  const quick=await all(env,'SELECT * FROM quick_replies WHERE tenant_id=? ORDER BY shortcut',[tid]),rules=await all(env,'SELECT * FROM automation_rules WHERE tenant_id=? ORDER BY id DESC',[tid]);const qrows=quick.map(q=>`<div class="list-row"><div><b>/${e(q.shortcut)}</b><small>${e(q.body.slice(0,100))}</small></div><form method="post">${csrfField(s)}<input type="hidden" name="action" value="quick_delete"><input type="hidden" name="id" value="${q.id}"><button class="btn small danger">Hapus</button></form></div>`).join('')||'<div class="empty">Belum ada quick reply.</div>',rrows=rules.map(r=>`<div class="list-row"><div><b>${e(r.name)}</b><small>${e(r.event_type)} → ${e(r.action_type)}</small></div><form method="post">${csrfField(s)}<input type="hidden" name="action" value="rule_delete"><input type="hidden" name="id" value="${r.id}"><button class="btn small danger">Hapus</button></form></div>`).join('')||'<div class="empty">Belum ada automation.</div>';
  return render(req,env,s,user,'Automation',`<div class="page-head"><div><span class="eyebrow">WORKFLOW</span><h1>Automation & Quick Reply</h1></div></div>${err?`<div class="alert error">${e(err)}</div>`:''}<div class="grid-2"><section class="panel"><h2>Quick Reply</h2><form method="post">${csrfField(s)}<input type="hidden" name="action" value="quick_add"><label>Shortcut<input name="shortcut" placeholder="cek_transaksi" required></label><label>Balasan<textarea name="body" required></textarea></label><button class="btn primary">Simpan</button></form>${qrows}</section><section class="panel"><h2>Automation Rule</h2><form method="post">${csrfField(s)}<input type="hidden" name="action" value="rule_add"><label>Nama<input name="name" required></label><label>Event<select name="event_type"><option>CHAT_NEW</option><option>VISITOR_NEW</option><option>DOMAIN_ADD</option></select></label><label>Action<select name="action_type"><option>telegram_notify</option><option>webhook</option><option>auto_reply</option></select></label><label>Pesan / payload<textarea name="message"></textarea></label><button class="btn primary">Tambah Rule</button></form>${rrows}</section></div>`,true);
}

async function apiWebhooksPage(req,env,ctx,s,user){if(!await can(env,user,'manage_api')&&user.role!=='owner')return forbidden();const tid=user.tenant_id;let err='',newKey='';if(req.method==='POST'){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else try{if(b.action==='api_add'){const raw='jlc_'+randomToken(32);newKey=raw;await insert(env,'INSERT INTO api_keys(tenant_id,name,key_hash,prefix,status,created_at) VALUES(?,?,?,?,\'active\',?)',[tid,cap(b.name,100),await sha256(raw),raw.slice(0,12),nowIso()]);await audit(env,ctx,{event:'API_KEY_CREATED',risk:30,metadata:{name:b.name},tenantId:tid,userId:user.id,request:req});}else if(b.action==='api_delete'){await run(env,'UPDATE api_keys SET status=\'revoked\' WHERE id=? AND tenant_id=?',[Number(b.id),tid]);await audit(env,ctx,{event:'API_KEY_REVOKED',risk:30,metadata:{id:Number(b.id)},tenantId:tid,userId:user.id,request:req});}else if(b.action==='hook_add'){if(!/^https:\/\//i.test(String(b.url||'')))throw new Error('Webhook wajib HTTPS.');const sec=randomToken(32);await insert(env,'INSERT INTO outbound_webhooks(tenant_id,name,url,secret_enc,event_types,status,created_at) VALUES(?,?,?,?,?,\'active\',?)',[tid,cap(b.name,100),cap(b.url,1000),await vaultEncrypt(env,sec),cap(b.events||'*',1000),nowIso()]);newKey=`Webhook signing secret: ${sec}`;await audit(env,ctx,{event:'OUTBOUND_WEBHOOK_CREATED',risk:30,tenantId:tid,userId:user.id,request:req});}else if(b.action==='hook_delete')await run(env,'DELETE FROM outbound_webhooks WHERE id=? AND tenant_id=?',[Number(b.id),tid]);}catch(x){err=x.message;}}
  const keys=await all(env,'SELECT * FROM api_keys WHERE tenant_id=? ORDER BY id DESC',[tid]),hooks=await all(env,'SELECT * FROM outbound_webhooks WHERE tenant_id=? ORDER BY id DESC',[tid]),krows=keys.map(k=>`<div class="list-row"><div><b>${e(k.name)}</b><small>${e(k.prefix)}•••• • ${e(k.status)}</small></div><form method="post">${csrfField(s)}<input type="hidden" name="action" value="api_delete"><input type="hidden" name="id" value="${k.id}"><button class="btn small danger">Revoke</button></form></div>`).join(''),hrows=hooks.map(h=>`<div class="list-row"><div><b>${e(h.name)}</b><small>${e(h.url)}</small></div><form method="post">${csrfField(s)}<input type="hidden" name="action" value="hook_delete"><input type="hidden" name="id" value="${h.id}"><button class="btn small danger">Hapus</button></form></div>`).join('');
  return render(req,env,s,user,'API & Webhooks',`<div class="page-head"><div><span class="eyebrow">DEVELOPER</span><h1>API & Outbound Webhook</h1></div></div>${err?`<div class="alert error">${e(err)}</div>`:''}${newKey?`<div class="alert ok"><b>Simpan sekarang. Secret hanya ditampilkan sekali.</b><code class="codebox">${e(newKey)}</code></div>`:''}<div class="grid-2"><section class="panel"><h2>API Keys</h2><form method="post">${csrfField(s)}<input type="hidden" name="action" value="api_add"><label>Nama key<input name="name" required></label><button class="btn primary">Buat API Key</button></form>${krows}</section><section class="panel"><h2>Outbound Webhook</h2><form method="post">${csrfField(s)}<input type="hidden" name="action" value="hook_add"><label>Nama<input name="name" required></label><label>HTTPS URL<input type="url" name="url" required></label><label>Events<input name="events" value="CHAT_NEW,LOGIN_SUCCESS" placeholder="* atau EVENT1,EVENT2"></label><button class="btn primary">Tambah Webhook</button></form>${hrows}</section></div><section class="panel"><h2>REST API</h2><code class="codebox">GET ${e(baseUrl(req))}/api/v1/chats\nPOST ${e(baseUrl(req))}/api/v1/chats/{id}/messages\nAuthorization: Bearer jlc_...</code></section>`,true);
}

async function subscriptionPage(req,env,ctx,s,user){if(!['owner','super_admin'].includes(user.role))return forbidden();const tid=user.tenant_id;if(req.method==='POST'){const b=await form(req);if(csrfOk(req,s,b)){const pid=Number(b.plan_id);if(!await one(env,"SELECT id FROM upgrade_requests WHERE tenant_id=? AND status='pending'",[tid]))await insert(env,"INSERT INTO upgrade_requests(tenant_id,plan_id,status,note,created_at) VALUES(?,?,'pending',?,?)",[tid,pid,cap(b.note,500),nowIso()]);await audit(env,ctx,{event:'UPGRADE_REQUEST',risk:10,metadata:{plan_id:pid},tenantId:tid,userId:user.id,request:req});flash(s,'ok','Permintaan upgrade dikirim ke admin.');}return redirect('/subscription');}const current=await currentPlan(env,tid),plans=await all(env,'SELECT * FROM plans WHERE is_active=1 ORDER BY price'),cards=plans.map(p=>`<div class="plan-card ${Number(current?.id)===Number(p.id)?'current':''}"><span class="pill">${e(p.name)}</span><h2>Rp ${money(p.price)}</h2><p>${p.domain_limit} domain • ${p.bot_limit} bot • ${p.agent_limit} user</p><form method="post">${csrfField(s)}<input type="hidden" name="plan_id" value="${p.id}"><button class="btn ${Number(current?.id)===Number(p.id)?'ghost':'primary'} full" ${Number(current?.id)===Number(p.id)?'disabled':''}>${Number(current?.id)===Number(p.id)?'Paket aktif':'Request Upgrade'}</button></form></div>`).join('');return render(req,env,s,user,'Subscription',`<div class="page-head"><div><span class="eyebrow">SUBSCRIPTION</span><h1>Upgrade Langganan</h1></div><div class="plan-chip">Berakhir ${e(String(current?.ends_at||'-').slice(0,10))}</div></div><div class="plan-grid">${cards}</div>`,true);}

async function diagnosticsPage(req,env,s,user){if(!await can(env,user,'diagnostics')&&user.role!=='owner')return forbidden();const tid=user.tenant_id,domains=await all(env,'SELECT * FROM domains WHERE tenant_id=?',[tid]);let rows='';for(const d of domains){const bot=await domainBot(env,d.id);let wh='not connected',botOk=false;if(bot){const r=await tgCall(bot.token,'getWebhookInfo');botOk=!!r.ok;wh=r.ok?(r.result?.url||'webhook empty'):(r.description||'error');}const checks=[['Domain status',d.status==='active',d.status],['Widget config',!!await one(env,'SELECT domain_id FROM widget_settings WHERE domain_id=?',[d.id]),'configured'],['Telegram bot',!!bot,bot?`@${bot.bot_username}`:'not connected'],['Telegram webhook',botOk,wh],['HTTPS Worker',true,baseUrl(req)]];rows+=`<section class="panel"><div class="panel-head"><h2>${e(d.domain)}</h2><span class="badge ${e(d.status)}">${e(d.status)}</span></div>${checks.map(x=>`<div class="diag-row"><span class="diag-icon ${x[1]?'ok':'bad'}">${x[1]?'✓':'!'}</span><div><b>${e(x[0])}</b><small>${e(x[2])}</small></div></div>`).join('')}</section>`;}
  const server=[['Runtime: Cloudflare Workers',true],['Database: D1',!!env.DB],['Storage: R2',!!env.UPLOADS],['Realtime: Durable Objects',!!env.LIVE_HUB],['Security Vault',await vaultReady(env)],['HTTPS',new URL(req.url).protocol==='https:'],['Cron maintenance',true]];return render(req,env,s,user,'Diagnostics',`<div class="page-head"><div><span class="eyebrow">SYSTEM DOCTOR</span><h1>Diagnosis & Troubleshooting</h1></div></div><section class="panel"><h2>Cloudflare health</h2>${server.map(x=>`<div class="diag-row"><span class="diag-icon ${x[1]?'ok':'bad'}">${x[1]?'✓':'!'}</span><b>${e(x[0])}</b></div>`).join('')}</section><div class="cards">${rows}</div><section class="panel"><h2>Tutorial cepat</h2><details><summary>Widget tidak tampil</summary><p>Pastikan domain status <b>active</b>, script memakai <code>data-site</code> yang benar, origin sama dengan domain terdaftar, dan halaman HTTPS.</p></details><details><summary>Chat tidak masuk Telegram</summary><p>Pastikan bot sudah pairing, domain dipetakan ke bot, webhook Telegram aktif, dan bot tidak dipakai domain lain.</p></details><details><summary>OTP tidak masuk</summary><p>Pastikan user menekan Start pada bot autentikasi. Cek Admin → Settings → getWebhookInfo.</p></details><details><summary>Error Cloudflare</summary><p>Jalankan <code>npx wrangler tail</code>. Pastikan D1/R2/Durable Objects berhasil diprovision otomatis.</p></details></section>`,true);}

async function settingsPage(req,env,ctx,s,user){let pref=await one(env,'SELECT * FROM user_preferences WHERE user_id=?',[user.id]);if(req.method==='POST'){const b=await form(req);if(csrfOk(req,s,b)){await run(env,'UPDATE users SET name=? WHERE id=?',[cap(b.name,120),user.id]);await run(env,'UPDATE user_preferences SET theme=?,sound=?,updated_at=? WHERE user_id=?',[['system','dark','light'].includes(b.theme)?b.theme:'system',['soft','crisp','digital','custom','none'].includes(b.sound)?b.sound:'soft',nowIso(),user.id]);await audit(env,ctx,{event:'ACCOUNT_SETTINGS_CHANGED',risk:10,tenantId:user.tenant_id,userId:user.id,request:req});flash(s,'ok','Pengaturan disimpan.');}return redirect('/settings');}pref=await one(env,'SELECT * FROM user_preferences WHERE user_id=?',[user.id]);return render(req,env,s,user,'Account Settings',`<div class="page-head"><div><span class="eyebrow">PROFILE</span><h1>Setting Akun</h1></div></div><div class="grid-2"><section class="panel"><form method="post">${csrfField(s)}<label>Nama<input name="name" value="${attr(user.name)}"></label><label>Email<input value="${attr(user.email)}" disabled></label><label>Theme<select name="theme"><option value="system"${selected(pref?.theme,'system')}>System</option><option value="dark"${selected(pref?.theme,'dark')}>Dark</option><option value="light"${selected(pref?.theme,'light')}>Light</option></select></label><label>Nada notifikasi<select name="sound"><option value="soft"${selected(pref?.sound,'soft')}>Soft</option><option value="crisp"${selected(pref?.sound,'crisp')}>Crisp</option><option value="digital"${selected(pref?.sound,'digital')}>Digital</option><option value="custom"${selected(pref?.sound,'custom')}>Custom</option><option value="none"${selected(pref?.sound,'none')}>Off</option></select></label><button class="btn primary">Simpan</button></form></section><section class="panel"><h2>Telegram Security</h2><div class="identity-card"><b>@${e(user.telegram_username||'belum-terhubung')}</b><small>ID ${e(user.telegram_user_id||'-')}</small><span class="badge ${user.telegram_verified_at?'active':'pending'}">${user.telegram_verified_at?'verified':'not linked'}</span></div><p class="muted">Telegram User ID menjadi identitas utama verifikasi, bukan username yang bisa berubah.</p></section></div>`,true);}

async function adminPage(req,env,ctx,s,user,url){if(user.role!=='super_admin')return forbidden();const p=url.pathname;
  if(p==='/admin'||p==='/admin/dashboard'){const counts={users:Number((await one(env,'SELECT COUNT(*) c FROM users'))?.c||0),tenants:Number((await one(env,'SELECT COUNT(*) c FROM tenants'))?.c||0),domains:Number((await one(env,'SELECT COUNT(*) c FROM domains'))?.c||0),online:Number((await one(env,'SELECT COUNT(*) c FROM visitors WHERE last_seen_at>=?',[new Date(Date.now()-90000).toISOString().replace('T',' ').replace('Z','').slice(0,19)]))?.c||0)},logs=await all(env,'SELECT * FROM audit_logs ORDER BY id DESC LIMIT 20'),rows=logs.map(l=>`<div class="list-row"><div><b>${e(l.event_type)}</b><small>${e(l.created_at)} • User #${e(l.user_id||'-')}</small></div><span class="risk ${Number(l.risk)>=50?'high':''}">${l.risk}</span></div>`).join('');return render(req,env,s,user,'Admin',`<div class="page-head"><div><span class="eyebrow">SUPER ADMIN • CLOUDFLARE</span><h1>Platform Overview</h1></div></div><div class="stats">${stat('Users',counts.users,'user')}${stat('Tenants',counts.tenants,'domain')}${stat('Domains',counts.domains,'domain')}${stat('Online',counts.online,'pulse')}</div><section class="panel"><div class="panel-head"><h2>Security Event Stream</h2><a href="/admin/logs">View logs</a></div>${rows}</section>`,true,true);}
  if(p==='/admin/settings')return adminSettingsPage(req,env,ctx,s,user);
  if(p==='/admin/users'){const rows=(await all(env,'SELECT u.*,t.name tenant_name FROM users u LEFT JOIN tenants t ON t.id=u.tenant_id ORDER BY u.id DESC LIMIT 300')).map(x=>`<div class="list-row"><div><b>${e(x.name)} • ${e(x.email)}</b><small>${e(x.tenant_name)} • ${e(x.role)}</small></div><span class="badge ${e(x.status)}">${e(x.status)}</span></div>`).join('');return render(req,env,s,user,'Admin Users',`<div class="page-head"><h1>Users</h1></div><section class="panel">${rows}</section>`,true,true);}
  if(p==='/admin/plans')return adminPlansPage(req,env,ctx,s,user);
  if(p==='/admin/subscriptions')return adminSubscriptionsPage(req,env,ctx,s,user);
  if(p==='/admin/logs'){const logs=await all(env,'SELECT * FROM audit_logs ORDER BY id DESC LIMIT 500'),rows=logs.map(l=>`<div class="list-row"><div><b>${e(l.event_type)}</b><small>User #${e(l.user_id||'-')} • ${e(l.ip||'')} • ${e(l.created_at)}</small></div><span class="risk ${Number(l.risk)>=50?'high':''}">${Number(l.risk)}</span></div>`).join('');return render(req,env,s,user,'Audit Logs',`<div class="page-head"><h1>Audit Logs</h1></div><section class="panel">${rows}</section>`,true,true);}
  return render(req,env,s,user,'Admin 404','<div class="empty">Admin page not found.</div>',true,true,404);
}

async function adminSettingsPage(req,env,ctx,s,user){let err='',info='';if(req.method==='POST'){const b=await form(req);if(!csrfOk(req,s,b))err='CSRF tidak valid.';else try{
    if(b.action==='auth_bot'){const token=normalizeToken(b.token),me=await tgCall(token,'getMe');if(!me.ok)throw new Error(me.transport_error?`Server Cloudflare gagal menghubungi Telegram: ${me.description}`:`Token bot autentikasi tidak valid: ${me.description||''}`);const username=me.result?.username||'',secret=secretToken(40);await saveAuthBot(env,{token,username,webhook_secret:secret});const wh=await tgCall(token,'setWebhook',{url:`${baseUrl(req)}/webhook/auth/${secret}`,secret_token:secret,drop_pending_updates:true,allowed_updates:['message']});if(!wh.ok)throw new Error(`setWebhook gagal: ${wh.description||'unknown'}`);const check=await tgCall(token,'getWebhookInfo');info=check.ok?`Webhook aktif: ${check.result?.url||'-'}`:'Webhook tersimpan, getWebhookInfo gagal.';await audit(env,ctx,{event:'AUTH_BOT_CHANGED',risk:50,metadata:{username},tenantId:user.tenant_id,userId:user.id,request:req});
    }else if(b.action==='link_admin'){const token=randomToken(40).slice(0,60);await run(env,"INSERT INTO telegram_links(user_id,token,purpose,expires_at,created_at) VALUES(?,?,'link_only',?,?)",[user.id,token,isoAfter(1800),nowIso()]);return redirect(`/telegram/connect?token=${encodeURIComponent(token)}`);
    }else if(b.action==='admin_bot_add'){const token=normalizeToken(b.token),me=await tgCall(token,'getMe');if(!me.ok)throw new Error(`Token tracking bot tidak valid: ${me.description||''}`);await insert(env,"INSERT INTO admin_bots(name,token_enc,chat_id,event_types,status,created_at) VALUES(?,?,?,?, 'active',?)",[cap(b.name,100),await vaultEncrypt(env,token),cap(b.chat_id,80),cap(b.events||'*',1000),nowIso()]);await audit(env,ctx,{event:'ADMIN_TRACKING_BOT_ADD',risk:40,metadata:{name:b.name},tenantId:user.tenant_id,userId:user.id,request:req});
    }else if(b.action==='admin_bot_delete'){await run(env,'DELETE FROM admin_bots WHERE id=?',[Number(b.id)]);}
    if(info)flash(s,'ok',info);return redirect('/admin/settings');
  }catch(x){err=x.message;}}
  const bot=await authBot(env),abots=await all(env,'SELECT id,name,chat_id,event_types,status,created_at FROM admin_bots ORDER BY id DESC'),ab=abots.map(x=>`<div class="list-row"><div><b>${e(x.name)}</b><small>${e(x.chat_id)} • ${e(x.event_types)}</small></div><form method="post">${csrfField(s)}<input type="hidden" name="action" value="admin_bot_delete"><input type="hidden" name="id" value="${x.id}"><button class="btn small danger">Hapus</button></form></div>`).join('')||'<div class="empty">Belum ada tracking bot.</div>';
  const content=`<div class="page-head"><div><span class="eyebrow">PLATFORM SETTINGS</span><h1>Bot & Security Router</h1></div></div>${err?`<div class="alert error">${e(err)}</div>`:''}${info?`<div class="alert ok">${e(info)}</div>`:''}<div class="grid-2"><section class="panel"><h2>Bot Autentikasi</h2><p class="muted">Pairing + OTP register/login/reset.</p><form method="post">${csrfField(s)}<input type="hidden" name="action" value="auth_bot"><label>Bot Token<input type="password" name="token" required autocomplete="off"></label><label>Bot Username<input value="${attr(bot?.username?`@${bot.username}`:'otomatis dari getMe')}" disabled></label><button class="btn primary">Simpan & Pasang Webhook</button></form><form method="post" style="margin-top:10px">${csrfField(s)}<input type="hidden" name="action" value="link_admin"><button class="btn ghost full">Hubungkan Telegram Admin</button></form></section><section class="panel"><h2>Admin Tracking Bot</h2><form method="post">${csrfField(s)}<input type="hidden" name="action" value="admin_bot_add"><label>Nama<input name="name" required></label><label>Token<input type="password" name="token" required></label><label>Chat ID<input name="chat_id" required></label><label>Event types<input name="events" value="LOGIN_SUCCESS,PASSWORD_RESET,DOMAIN_ADD,BOT_ADD" placeholder="* atau EVENT1,EVENT2"></label><button class="btn primary">Tambah Bot</button></form></section></div><section class="panel"><h2>Tracking bots</h2>${ab}</section>`;
  return render(req,env,s,user,'Admin Settings',content,true,true);
}

async function adminPlansPage(req,env,ctx,s,user){if(req.method==='POST'){const b=await form(req);if(csrfOk(req,s,b)){await run(env,'UPDATE plans SET price=?,duration_days=?,domain_limit=?,bot_limit=?,agent_limit=?,history_days=?,is_active=? WHERE id=?',[safeInt(b.price),safeInt(b.duration_days,30),safeInt(b.domain_limit,1),safeInt(b.bot_limit,1),safeInt(b.agent_limit,1),safeInt(b.history_days,30),b.is_active?1:0,Number(b.id)]);await audit(env,ctx,{event:'PLAN_CHANGED',risk:50,metadata:{plan_id:Number(b.id)},tenantId:user.tenant_id,userId:user.id,request:req});}return redirect('/admin/plans');}const plans=await all(env,'SELECT * FROM plans ORDER BY price'),cards=plans.map(x=>`<form method="post" class="panel">${csrfField(s)}<input type="hidden" name="id" value="${x.id}"><h2>${e(x.name)}</h2><div class="form-grid"><label>Harga<input type="number" name="price" value="${x.price}"></label><label>Hari<input type="number" name="duration_days" value="${x.duration_days}"></label><label>Domain<input type="number" name="domain_limit" value="${x.domain_limit}"></label><label>Bot<input type="number" name="bot_limit" value="${x.bot_limit}"></label><label>User<input type="number" name="agent_limit" value="${x.agent_limit}"></label><label>History<input type="number" name="history_days" value="${x.history_days}"></label></div><label class="switch-row"><input type="checkbox" name="is_active" value="1"${checked(x.is_active)}> Aktif</label><button class="btn primary">Simpan Plan</button></form>`).join('');return render(req,env,s,user,'Admin Plans',`<div class="page-head"><h1>Plan Builder</h1></div><div class="cards">${cards}</div>`,true,true);}

async function adminSubscriptionsPage(req,env,ctx,s,user){if(req.method==='POST'){const b=await form(req);if(csrfOk(req,s,b)){const rid=Number(b.request_id),r=await one(env,'SELECT ur.*,p.duration_days FROM upgrade_requests ur JOIN plans p ON p.id=ur.plan_id WHERE ur.id=?',[rid]);if(r){await run(env,"UPDATE subscriptions SET status='expired' WHERE tenant_id=? AND status IN ('active','trial')",[r.tenant_id]);await insert(env,"INSERT INTO subscriptions(tenant_id,plan_id,status,starts_at,ends_at,created_at) VALUES(?,?,'active',?,?,?)",[r.tenant_id,r.plan_id,nowIso(),isoAfter(Number(r.duration_days)*86400),nowIso()]);await run(env,"UPDATE upgrade_requests SET status='approved',decided_at=? WHERE id=?",[nowIso(),rid]);await audit(env,ctx,{event:'SUBSCRIPTION_APPROVED',risk:30,metadata:{request_id:rid},tenantId:r.tenant_id,userId:user.id,request:req});}}return redirect('/admin/subscriptions');}const rr=await all(env,'SELECT ur.*,t.name tenant_name,p.name plan_name FROM upgrade_requests ur JOIN tenants t ON t.id=ur.tenant_id JOIN plans p ON p.id=ur.plan_id ORDER BY ur.id DESC'),rows=rr.map(r=>`<div class="list-row"><div><b>${e(r.tenant_name)} → ${e(r.plan_name)}</b><small>${e(r.created_at)}</small></div>${r.status==='pending'?`<form method="post">${csrfField(s)}<input type="hidden" name="request_id" value="${r.id}"><button class="btn small primary">Approve</button></form>`:`<span class="badge active">${e(r.status)}</span>`}</div>`).join('');return render(req,env,s,user,'Subscriptions',`<div class="page-head"><h1>Subscription Requests</h1></div><section class="panel">${rows}</section>`,true,true);}

async function webhookRoute(req,env,ctx,url){
  const authMatch=url.pathname.match(/^\/webhook\/auth\/([A-Za-z0-9_-]+)$/);if(authMatch)return authWebhook(req,env,ctx,authMatch[1]);
  const botMatch=url.pathname.match(/^\/webhook\/bot\/(\d+)\/([A-Za-z0-9_-]+)$/);if(botMatch)return botWebhook(req,env,ctx,Number(botMatch[1]),botMatch[2]);return json({ok:false},404);
}

async function authWebhook(req,env,ctx,pathSecret){
  const bot=await authBot(env);if(!bot||bot.webhook_secret!==pathSecret)return json({ok:false},403);const got=req.headers.get('x-telegram-bot-api-secret-token')||'';if(got!==pathSecret)return json({ok:false},403);const up=await req.json().catch(()=>({})),msg=up.message;if(!msg?.text)return json({ok:true});const m=msg.text.match(/^\/start\s+([A-Za-z0-9_-]{8,80})/);if(m){const link=await one(env,'SELECT * FROM telegram_links WHERE token=?',[m[1]]);const ok=await pairTelegram(env,ctx,req,m[1],msg.from,msg.chat?.id);if(ok){const note=link?.purpose==='link_only'?'✅ Telegram berhasil dihubungkan ke akun.':'✅ Telegram berhasil terhubung. OTP verifikasi sudah dikirim.';await tgSend(bot.token,String(msg.chat.id),note);}}return json({ok:true});
}

async function botWebhook(req,env,ctx,id,pathSecret){
  const b=await one(env,"SELECT * FROM bots WHERE id=? AND status='active'",[id]);if(!b||b.webhook_secret!==pathSecret)return json({ok:false},403);if((req.headers.get('x-telegram-bot-api-secret-token')||'')!==pathSecret)return json({ok:false},403);const up=await req.json().catch(()=>({})),msg=up.message;if(!msg?.text)return json({ok:true});
  const bind=msg.text.match(/^\/(?:start\s+bind_|bind\s+)([A-Za-z0-9_-]+)/);if(bind&&bind[1]===b.bind_token){await run(env,'UPDATE bots SET notification_chat_id=? WHERE id=?',[String(msg.chat.id),id]);const token=await vaultDecrypt(env,b.token_enc);await tgSend(token,String(msg.chat.id),'✅ Bot live chat berhasil dihubungkan. Chat dari website akan masuk ke percakapan ini.');await audit(env,ctx,{event:'BOT_CHAT_BOUND',risk:10,metadata:{bot_id:id,chat_id:String(msg.chat.id)},tenantId:b.tenant_id,request:req});return json({ok:true});}
  if(b.notification_chat_id&&String(msg.chat?.id)!==String(b.notification_chat_id))return json({ok:true});let chat=null,body=msg.text;
  if(msg.reply_to_message?.message_id)chat=await one(env,'SELECT c.*,v.visitor_key FROM messages m JOIN chats c ON c.id=m.chat_id JOIN visitors v ON v.id=c.visitor_id JOIN domain_bots db ON db.domain_id=c.domain_id WHERE m.telegram_message_id=? AND db.bot_id=? ORDER BY m.id DESC LIMIT 1',[String(msg.reply_to_message.message_id),id]);
  if(!chat){const mm=body.match(/^\/reply\s+([A-Z0-9]{6,12})\s+([\s\S]+)/);if(mm){chat=await one(env,'SELECT c.*,v.visitor_key FROM chats c JOIN visitors v ON v.id=c.visitor_id JOIN domain_bots db ON db.domain_id=c.domain_id WHERE c.code=? AND db.bot_id=?',[mm[1],id]);body=mm[2];}}
  if(chat&&body.trim()){const mid=await insert(env,"INSERT INTO messages(chat_id,sender_type,sender_id,body,created_at) VALUES(?,'agent',?,?,?)",[chat.id,`telegram:${msg.from?.id||''}`,cap(body.trim(),3500),nowIso()]);await run(env,'UPDATE chats SET updated_at=? WHERE id=?',[nowIso(),chat.id]);await hubBroadcast(env,chat.domain_id,{type:'message',id:mid,chat_id:chat.id,visitor_key:chat.visitor_key,sender_type:'agent',body:cap(body.trim(),3500),created_at:nowIso()});await audit(env,ctx,{event:'TELEGRAM_REPLY',risk:5,metadata:{chat:chat.code},tenantId:b.tenant_id,request:req});}
  return json({ok:true});
}

async function parseWidgetBody(req){if(req.method==='GET')return {};const raw=await req.text();if(!raw)return {};try{return JSON.parse(raw)}catch{return {}}}
function corsHeaders(req,domain){const origin=req.headers.get('origin')||'';const h={'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type','access-control-max-age':'86400','vary':'Origin'};if(origin&&sameDomain(originHost(origin),domain))h['access-control-allow-origin']=origin;return h;}
function widgetOriginOk(req,domain){const source=req.headers.get('origin')||req.headers.get('referer')||'';return !source||sameDomain(originHost(source),domain);}
function widgetJson(req,domain,data,status=200){return json(data,status,corsHeaders(req,domain));}
async function widgetSite(env,site){return one(env,`SELECT d.*,ws.title,ws.welcome,ws.position,ws.theme,ws.accent,ws.icon,ws.custom_icon_key,ws.require_name,ws.require_phone,ws.require_email,ws.offline_message,ws.business_hours_json,ws.launcher_label FROM domains d JOIN widget_settings ws ON ws.domain_id=d.id WHERE d.public_key=? AND d.status='active'`,[site]);}

async function widgetApi(req,env,ctx,url){
  const payload=await parseWidgetBody(req),site=String(payload.site||url.searchParams.get('site')||''),d=await widgetSite(env,site);if(req.method==='OPTIONS')return d?new Response(null,{status:204,headers:corsHeaders(req,d.domain)}):new Response(null,{status:204});if(!d)return json({ok:false,error:'invalid_site'},404);if(!widgetOriginOk(req,d.domain))return widgetJson(req,d.domain,{ok:false,error:'origin_not_allowed'},403);const p=url.pathname;
  if(p==='/api/widget/bootstrap'){let vk=String(payload.visitor_key||'').replace(/[^A-Za-z0-9_-]/g,'');if(vk.length<12)vk=randomToken(18);const v=await touchVisitor(req,env,ctx,d,vk,payload);const open=isBusinessOpen(d.business_hours_json);return widgetJson(req,d.domain,{ok:true,visitor_key:vk,settings:{title:d.title,welcome:open?d.welcome:d.offline_message,position:d.position,theme:d.theme,accent:d.accent,icon:d.icon,custom_icon_url:d.custom_icon_key?`/widget-media/${encodeURIComponent(d.custom_icon_key)}`:null,launcher_label:d.launcher_label,require_name:!!d.require_name,require_phone:!!d.require_phone,require_email:!!d.require_email,online:open}});}
  if(p==='/api/widget/heartbeat'){await touchVisitor(req,env,ctx,d,String(payload.visitor_key||''),payload);return widgetJson(req,d.domain,{ok:true});}
  if(p==='/api/widget/message'){
    const rateKey=await sha256(`${d.id}:${String(payload.visitor_key||'anon')}:${clientIp(req)}`);
    if(!await allowRate(env,'widget_message',rateKey,30,60))return widgetJson(req,d.domain,{ok:false,error:'rate_limited'},429);
    const plan=await currentPlan(env,d.tenant_id);if(!plan)return widgetJson(req,d.domain,{ok:false,error:'subscription_inactive'},402);const body=String(payload.body||'').trim();if(!body||body.length>3500)return widgetJson(req,d.domain,{ok:false,error:'invalid_message'},422);if(d.require_name&&!String(payload.name||'').trim())return widgetJson(req,d.domain,{ok:false,error:'name_required'},422);if(d.require_phone&&!String(payload.phone||'').trim())return widgetJson(req,d.domain,{ok:false,error:'phone_required'},422);if(d.require_email&&!String(payload.email||'').trim())return widgetJson(req,d.domain,{ok:false,error:'email_required'},422);
    const v=await touchVisitor(req,env,ctx,d,String(payload.visitor_key||''),payload);let chat=await one(env,"SELECT * FROM chats WHERE domain_id=? AND visitor_id=? AND status='open' ORDER BY id DESC LIMIT 1",[d.id,v.id]);let fresh=false;if(!chat){const code=chatCode(),cid=await insert(env,"INSERT INTO chats(domain_id,visitor_id,code,name,phone,email,status,created_at,updated_at) VALUES(?,?,?,?,?,?,'open',?,?)",[d.id,v.id,code,cap(payload.name,100),cap(payload.phone,40),cap(payload.email,160),nowIso(),nowIso()]);chat=await one(env,'SELECT * FROM chats WHERE id=?',[cid]);fresh=true;await audit(env,ctx,{event:'CHAT_NEW',risk:5,metadata:{domain:d.domain,chat:chat.code},tenantId:d.tenant_id,request:req});}
    const mid=await insert(env,"INSERT INTO messages(chat_id,sender_type,body,created_at) VALUES(?,'visitor',?,?)",[chat.id,body,nowIso()]);await run(env,'UPDATE chats SET updated_at=? WHERE id=?',[nowIso(),chat.id]);const bot=await domainBot(env,d.id);if(bot?.notification_chat_id){const txt=`💬 <b>LIVE CHAT #${e(chat.code)}</b>\nDomain: ${e(d.domain)}\nVisitor: ${e(chat.name||'Anonymous')}\n\n${e(body)}\n\nBalas pesan ini untuk reply ke visitor.`;const tr=await tgSend(bot.token,bot.notification_chat_id,txt);if(tr.ok)await run(env,'UPDATE messages SET telegram_message_id=? WHERE id=?',[String(tr.result?.message_id||''),mid]);}
    await hubBroadcast(env,d.id,{type:'message',id:mid,chat_id:chat.id,visitor_key:v.visitor_key,sender_type:'visitor',body,created_at:nowIso()});if(fresh)ctx.waitUntil(runAutomations(env,ctx,'CHAT_NEW',d.tenant_id,{domainId:d.id,chatId:chat.id,visitorKey:v.visitor_key,chatCode:chat.code}).catch(()=>{}));return widgetJson(req,d.domain,{ok:true,chat_code:chat.code,message_id:mid});
  }
  if(p==='/api/widget/poll'){const vk=String(url.searchParams.get('visitor_key')||payload.visitor_key||''),after=Number(url.searchParams.get('after')||0),v=await one(env,'SELECT * FROM visitors WHERE domain_id=? AND visitor_key=?',[d.id,vk]);if(!v)return widgetJson(req,d.domain,{ok:true,messages:[]});const chat=await one(env,"SELECT * FROM chats WHERE domain_id=? AND visitor_id=? AND status='open' ORDER BY id DESC LIMIT 1",[d.id,v.id]);if(!chat)return widgetJson(req,d.domain,{ok:true,messages:[]});const msgs=await all(env,'SELECT id,sender_type,body,created_at FROM messages WHERE chat_id=? AND id>? ORDER BY id ASC',[chat.id,after]);return widgetJson(req,d.domain,{ok:true,messages:msgs,chat_id:chat.id});}
  return widgetJson(req,d.domain,{ok:false},404);
}


async function allowRate(env,bucket,key,limit,windowSeconds){
  const now=Date.now(),row=await one(env,'SELECT count,expires_at FROM rate_limits WHERE bucket=? AND window_key=?',[bucket,key]);
  if(!row||Date.parse(String(row.expires_at||''))<=now){await run(env,`INSERT INTO rate_limits(bucket,window_key,count,expires_at) VALUES(?,?,1,?) ON CONFLICT(bucket,window_key) DO UPDATE SET count=1,expires_at=excluded.expires_at`,[bucket,key,new Date(now+windowSeconds*1000).toISOString()]);return true;}
  if(Number(row.count||0)>=limit)return false;
  await run(env,'UPDATE rate_limits SET count=count+1 WHERE bucket=? AND window_key=?',[bucket,key]);return true;
}

async function touchVisitor(req,env,ctx,d,vk,payload){if(String(vk).length<8)vk=randomToken(18);const ipHash=await vaultDigest(env,clientIp(req)),url=cap(payload.url,1000),ref=cap(payload.referrer,1000);let v=await one(env,'SELECT * FROM visitors WHERE domain_id=? AND visitor_key=?',[d.id,vk]);if(!v){const id=await insert(env,"INSERT INTO visitors(domain_id,visitor_key,ip_hash,user_agent,referrer,last_url,country,status,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,?,?,'online',?,?)",[d.id,vk,ipHash,ua(req),ref,url,cfCountry(req),nowIso(),nowIso()]);v=await one(env,'SELECT * FROM visitors WHERE id=?',[id]);if(url)await insert(env,'INSERT INTO pageviews(domain_id,visitor_id,url,referrer,created_at) VALUES(?,?,?,?,?)',[d.id,id,url,ref,nowIso()]);await audit(env,ctx,{event:'VISITOR_NEW',risk:0,metadata:{domain:d.domain,url},tenantId:d.tenant_id,request:req});ctx.waitUntil(runAutomations(env,ctx,'VISITOR_NEW',d.tenant_id,{domainId:d.id,visitorKey:vk,url}).catch(()=>{}));}else{if(url&&url!==v.last_url)await insert(env,'INSERT INTO pageviews(domain_id,visitor_id,url,referrer,created_at) VALUES(?,?,?,?,?)',[d.id,v.id,url,ref,nowIso()]);await run(env,"UPDATE visitors SET last_url=?,last_seen_at=?,country=?,status='online' WHERE id=?",[url,nowIso(),cfCountry(req),v.id]);v={...v,last_url:url,last_seen_at:nowIso()};}return v;}

function isBusinessOpen(raw){let h={};try{h=JSON.parse(raw||'{}')}catch{};const entries=Object.entries(h).filter(([k])=>['mon','tue','wed','thu','fri','sat','sun'].includes(k));if(!entries.length||entries.every(([,v])=>!v))return true;const zone=h.timezone||'Asia/Jakarta';let parts;try{parts=new Intl.DateTimeFormat('en-GB',{timeZone:zone,weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date())}catch{return true}const day=(parts.find(x=>x.type==='weekday')?.value||'Mon').slice(0,3).toLowerCase(),hh=parts.find(x=>x.type==='hour')?.value||'00',mm=parts.find(x=>x.type==='minute')?.value||'00',range=h[day];if(!range)return false;const m=String(range).match(/^(\d{2}:\d{2})-(\d{2}:\d{2})$/);if(!m)return true;const cur=`${hh}:${mm}`;return cur>=m[1]&&cur<=m[2];}

async function runAutomations(env,ctx,event,tenantId,data){const rules=await all(env,'SELECT * FROM automation_rules WHERE tenant_id=? AND event_type=? AND enabled=1',[tenantId,event]);for(const r of rules){let a={};try{a=JSON.parse(r.action_json||'{}')}catch{};if(r.action_type==='auto_reply'&&data.chatId&&a.message){const mid=await insert(env,"INSERT INTO messages(chat_id,sender_type,sender_id,body,created_at) VALUES(?,'agent','automation',?,?)",[data.chatId,cap(a.message,1000),nowIso()]);await hubBroadcast(env,data.domainId,{type:'message',id:mid,chat_id:data.chatId,visitor_key:data.visitorKey,sender_type:'agent',body:cap(a.message,1000),created_at:nowIso()});}else if(r.action_type==='telegram_notify'&&data.domainId){const bot=await domainBot(env,data.domainId);if(bot?.notification_chat_id)await tgSend(bot.token,bot.notification_chat_id,`⚡ Automation: ${e(r.name)}\nEvent: ${e(event)}\n${e(a.message||'')}`);}}
}

async function dashboardApi(req,env,ctx,url,s,user){
  const p=url.pathname;if(p==='/api/dashboard/telegram-status'){const token=url.searchParams.get('token')||'',r=await one(env,'SELECT u.telegram_verified_at FROM telegram_links tl JOIN users u ON u.id=tl.user_id WHERE tl.token=?',[token]);return json({ok:true,paired:!!r?.telegram_verified_at});}
  if(!user)return json({ok:false,error:'unauthorized'},401);
  if(p==='/api/dashboard/reply'){
    if(!await can(env,user,'reply_chat'))return json({ok:false,error:'forbidden'},403);const b=await form(req);if(!csrfOk(req,s,b))return json({ok:false,error:'csrf'},403);const cid=Number(b.chat_id||0),body=String(b.body||'').trim();const chat=await one(env,'SELECT c.*,d.tenant_id,v.visitor_key FROM chats c JOIN domains d ON d.id=c.domain_id JOIN visitors v ON v.id=c.visitor_id WHERE c.id=? AND d.tenant_id=?',[cid,user.tenant_id]);if(!chat||!body)return json({ok:false},422);const id=await insert(env,"INSERT INTO messages(chat_id,sender_type,sender_id,body,created_at) VALUES(?,'agent',?,?,?)",[cid,String(user.id),cap(body,3500),nowIso()]);await run(env,'UPDATE chats SET updated_at=? WHERE id=?',[nowIso(),cid]);await hubBroadcast(env,chat.domain_id,{type:'message',id,chat_id:cid,visitor_key:chat.visitor_key,sender_type:'agent',body:cap(body,3500),created_at:nowIso()});return json({ok:true,id});
  }
  if(p==='/api/dashboard/messages'){if(!await can(env,user,'view_chat'))return json({ok:false,error:'forbidden'},403);const cid=Number(url.searchParams.get('chat_id')||0),after=Number(url.searchParams.get('after')||0),valid=await one(env,'SELECT c.id FROM chats c JOIN domains d ON d.id=c.domain_id WHERE c.id=? AND d.tenant_id=?',[cid,user.tenant_id]);if(!valid)return json({ok:false},403);return json({ok:true,messages:await all(env,'SELECT id,sender_type,body,created_at FROM messages WHERE chat_id=? AND id>? ORDER BY id',[cid,after])});}
  if(p==='/api/dashboard/bot-status'){const id=Number(url.searchParams.get('id')||0),b=await one(env,'SELECT notification_chat_id FROM bots WHERE id=? AND tenant_id=?',[id,user.tenant_id]);return json({ok:!!b,paired:!!b?.notification_chat_id});}
  return json({ok:false},404);
}

async function wsWidget(req,env,url){
  if(req.headers.get('Upgrade')!=='websocket')return text('Upgrade required',426);const site=url.searchParams.get('site')||'',vk=url.searchParams.get('visitor_key')||'',d=await widgetSite(env,site);if(!d||!widgetOriginOk(req,d.domain))return text('Forbidden',403);const v=await one(env,'SELECT id FROM visitors WHERE domain_id=? AND visitor_key=?',[d.id,vk]);if(!v)return text('Unknown visitor',404);const stub=hubStub(env,d.id),h=new Headers(req.headers),target=`https://hub/connect?role=visitor&visitor_key=${encodeURIComponent(vk)}`;return stub.fetch(new Request(target,{method:'GET',headers:h}));
}
async function wsDashboard(req,env,url,s,user){
  if(!user||!await can(env,user,'view_chat'))return text('Forbidden',403);if(req.headers.get('Upgrade')!=='websocket')return text('Upgrade required',426);const cid=Number(url.searchParams.get('chat_id')||0),chat=await one(env,'SELECT c.id,c.domain_id FROM chats c JOIN domains d ON d.id=c.domain_id WHERE c.id=? AND d.tenant_id=?',[cid,user.tenant_id]);if(!chat)return text('Not found',404);const stub=hubStub(env,chat.domain_id),h=new Headers(req.headers),target=`https://hub/connect?role=agent&chat_id=${cid}&user_id=${user.id}`;return stub.fetch(new Request(target,{method:'GET',headers:h}));
}

async function mediaRoute(req,env,url,user){if(!user)return text('Unauthorized',401);const key=decodeURIComponent(url.pathname.slice('/media/'.length));const row=await one(env,'SELECT * FROM media_assets WHERE r2_key=? AND (tenant_id=? OR user_id=?)',[key,user.tenant_id,user.id]);if(!row)return text('Not found',404);const obj=await env.UPLOADS.get(key);if(!obj)return text('Not found',404);const h=new Headers();obj.writeHttpMetadata(h);h.set('cache-control','private,max-age=3600');return new Response(obj.body,{headers:h});}
async function widgetMedia(req,env,url){const key=decodeURIComponent(url.pathname.slice('/widget-media/'.length));const row=await one(env,"SELECT * FROM media_assets WHERE r2_key=? AND kind='widget_icon'",[key]);if(!row)return text('Not found',404);const obj=await env.UPLOADS.get(key);if(!obj)return text('Not found',404);const h=new Headers();obj.writeHttpMetadata(h);h.set('cache-control','public,max-age=86400');h.set('access-control-allow-origin','*');return new Response(obj.body,{headers:h});}

async function apiV1(req,env,ctx,url){
  const auth=req.headers.get('authorization')||'',m=auth.match(/^Bearer\s+(.+)$/i);if(!m)return json({ok:false,error:'missing_api_key'},401);const key=m[1],hash=await sha256(key),row=await one(env,"SELECT * FROM api_keys WHERE key_hash=? AND status='active'",[hash]);if(!row)return json({ok:false,error:'invalid_api_key'},401);await run(env,'UPDATE api_keys SET last_used_at=? WHERE id=?',[nowIso(),row.id]);const tid=row.tenant_id;
  if(url.pathname==='/api/v1/chats'&&req.method==='GET'){const chats=await all(env,'SELECT c.*,d.domain FROM chats c JOIN domains d ON d.id=c.domain_id WHERE d.tenant_id=? ORDER BY c.updated_at DESC LIMIT 200',[tid]);return json({ok:true,chats});}
  const mm=url.pathname.match(/^\/api\/v1\/chats\/(\d+)\/messages$/);if(mm&&req.method==='GET'){const chat=await one(env,'SELECT c.id FROM chats c JOIN domains d ON d.id=c.domain_id WHERE c.id=? AND d.tenant_id=?',[Number(mm[1]),tid]);if(!chat)return json({ok:false},404);return json({ok:true,messages:await all(env,'SELECT * FROM messages WHERE chat_id=? ORDER BY id',[chat.id])});}
  if(mm&&req.method==='POST'){const chat=await one(env,'SELECT c.*,v.visitor_key FROM chats c JOIN domains d ON d.id=c.domain_id JOIN visitors v ON v.id=c.visitor_id WHERE c.id=? AND d.tenant_id=?',[Number(mm[1]),tid]);if(!chat)return json({ok:false},404);const b=await req.json().catch(()=>({})),body=String(b.body||'').trim();if(!body)return json({ok:false,error:'body_required'},422);const id=await insert(env,"INSERT INTO messages(chat_id,sender_type,sender_id,body,created_at) VALUES(?,'agent','api',?,?)",[chat.id,cap(body,3500),nowIso()]);await hubBroadcast(env,chat.domain_id,{type:'message',id,chat_id:chat.id,visitor_key:chat.visitor_key,sender_type:'agent',body:cap(body,3500),created_at:nowIso()});await audit(env,ctx,{event:'API_CHAT_REPLY',risk:10,metadata:{chat_id:chat.id},tenantId:tid,request:req});return json({ok:true,id});}
  return json({ok:false,error:'not_found'},404);
}

async function maintenance(env,cron){const t=nowIso(),offline=new Date(Date.now()-120000).toISOString().replace('T',' ').replace('Z','').slice(0,19);await env.DB.batch([
  env.DB.prepare("UPDATE visitors SET status='offline' WHERE last_seen_at<? AND status<>'offline'").bind(offline),
  env.DB.prepare('DELETE FROM sessions WHERE expires_at<?').bind(t),
  env.DB.prepare('DELETE FROM otp_codes WHERE created_at<?').bind(new Date(Date.now()-86400000).toISOString().replace('T',' ').replace('Z','').slice(0,19)),
  env.DB.prepare('DELETE FROM login_attempts WHERE created_at<?').bind(new Date(Date.now()-7*86400000).toISOString().replace('T',' ').replace('Z','').slice(0,19)),
  env.DB.prepare('DELETE FROM rate_limits WHERE expires_at<?').bind(t),
  env.DB.prepare("UPDATE subscriptions SET status='expired' WHERE status IN ('active','trial') AND ends_at<=?").bind(t)
]);
  if(String(cron).includes('17 3')){const subs=await all(env,"SELECT s.tenant_id,p.history_days FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.status IN ('active','trial') AND s.ends_at>?",[t]);for(const x of subs){const cutoff=new Date(Date.now()-Number(x.history_days||30)*86400000).toISOString().replace('T',' ').replace('Z','').slice(0,19);await run(env,'DELETE FROM messages WHERE chat_id IN (SELECT c.id FROM chats c JOIN domains d ON d.id=c.domain_id WHERE d.tenant_id=?) AND created_at<?',[x.tenant_id,cutoff]);}await run(env,'DELETE FROM pageviews WHERE created_at<?',[new Date(Date.now()-180*86400000).toISOString().replace('T',' ').replace('Z','').slice(0,19)]);}
}
